# Datakwaliteit Archeologische Complexenbestand
auteur: Thya van den Berg

Organisatie: Rijksdienst voor het cultureel erfgoed

Programma: DNA-NL

Project: Bronnen- en datakwaliteit

Projectleider: Maurice de Kleijn

In dit notebook wordt het bestand DEF_complexen_v8 beoordeeld op datakwaliteit, volgens de datakwaliteitsrichtlijnen van Bronnen- en Datakwaliteit. Dit staat naast de beoordeling en suggesties die gedaan zijn vanuit de afdeling Archeologie in het bestand "reparatie en homogenisering complexenbestand". DEF_complexen_v8 bevat archaeologische complexen welke geassocieerd zijn met archeologische rijksmonumenten. Het is een kennisbestand dat geen verdere wettelijke waarde heeft, maar het heeft wel identificerende waarde, omdat hierin de werkelijk aanwezige archeologie binnen- of direct geassocieerd aan een rijksmonument wordt omschreven.

## Installeer packages (niet relevant voor non-programmeerder)

In [1]:
# %pip install duckdb
# %pip install matplotlib
# %pip install mpl_toolkits
# %pip install shapely
%pip install sparqlwrapper

Requirement already satisfied: sparqlwrapper in .\.venv\Lib\site-packages (2.0.0)
Requirement already satisfied: rdflib>=6.1.1 in .\.venv\Lib\site-packages (from sparqlwrapper) (7.6.0)
Requirement already satisfied: pyparsing<4,>=2.1.0 in .\.venv\Lib\site-packages (from rdflib>=6.1.1->sparqlwrapper) (3.3.2)
Note: you may need to restart the kernel to use updated packages.

## Laad packages (niet relevant voor non-programmeerder)

In [2]:
import duckdb
import inspect
import geopandas as gpd
import pandas as pd
import os
import matplotlib.pyplot as plt
from _duckdb import BinderException
from shapely import wkt
from SPARQLWrapper import SPARQLWrapper, JSON

## settings voor het bekijken van output

In [3]:
pd.set_option('display.max_columns', 50)
pd.set_option('display.max_rows', 100)

## Benodigde variabelen (niet relevant voor non-programmeerder)

### Voor medallion architecture

In [4]:
### Variabelen definiëren voor Medallion Architecture
datalake_path = os.path.normpath("./data/")
zilveren_laag_path = "zilver"

### Voor opslaan

In [5]:
# voor tussendoor opslaan
save_directory = os.path.normpath(r"./data/saved_parquet_files//")
if not os.path.exists(save_directory):
    # maak directory als deze nog niet bestaat
    os.mkdir(save_directory)

# voor opslaan "quick wins"
zilver_directory = os.path.normpath(f"./data/{zilveren_laag_path}//")
if not os.path.exists(zilver_directory):
    # maak directory als deze nog niet bestaat
    os.mkdir(zilver_directory)

## Benodigde functies (niet relevant voor non-programmeerder)

In [6]:
# sla output van een query op (template)
# file_name = 'query_output.parquet'
# duckdb.sql(f"""
#             COPY
#                 (SELECT x.*, y.*
#                 FROM
#                 brons_beschermde_stads_en_dorpsgezichten.townscapes x
#                 JOIN
#                 brons_rijksmonumentenregister.tblTEXT_OBJECT y
#                 ON
#                 x.bron_id = y.OBJ_NUMMER)
#                 TO '{os.path.join(save_directory, file_name)}'
#                 (FORMAT parquet);""")
#
# # alternatief
# duckdb.sql(f"""SELECT x.*, y.*
#                 FROM
#                 brons_beschermde_stads_en_dorpsgezichten.townscapes x
#                 JOIN
#                 brons_rijksmonumentenregister.tblTEXT_OBJECT y
#                 ON
#                 x.bron_id = y.OBJ_NUMMER""").write_parquet(os.path.join(save_directory, file_name))

def empty_duckdb_memory():
    """Empty the in-memory duckdb database"""
    schemas = duckdb.sql("""
                SELECT schema_name
                FROM information_schema.schemata
                WHERE schema_name NOT IN ('information_schema', 'pg_catalog', 'temp', 'main')""").fetchdf()
    for schema in schemas['schema_name']:
        tables = duckdb.sql(f"""
                        SELECT table_name
                        FROM information_schema.tables
                        WHERE table_schema = '{schema}'
        """).fetchdf()
        for table in tables['table_name']:
            duckdb.sql(f"DROP TABLE IF EXISTS {schema}.{table}")
        duckdb.sql(f"DROP SCHEMA IF EXISTS {schema}")


def save_complete_duckdb_memory(save_directory):
    """saves entire in-memory duckdb database to the given save_directory"""
    duckdb.sql(f"""EXPORT DATABASE '{save_directory}' (FORMAT parquet)""")

def load_duckdbset_to_memory(load_directory):
    """Loads an entire saved set of parquet files from the included "schema.sql" and "load.sql" files."""
    file_name = 'schema.sql'
    with open(os.path.join(load_directory, file_name), 'r') as schema:
        duckdb.sql(schema.read())

    file_name = 'load.sql'
    with open(os.path.join(load_directory, file_name), 'r') as load:
        duckdb.sql(load.read())
    duckdb.sql("SHOW SCHEMAS;")

### Initieer SPARQLwrappers
Connectie met linked data, voor datastandaarden

In [7]:
sparql_ABR = SPARQLWrapper(
    "https://data.cultureelerfgoed.nl/term/id/abr/2/b402446a-0a00-4fee-a9cd-1a7f307d651e")

print(f"endpoint support json: {sparql_ABR.supportsReturnFormat('json')}")

sparql_ABR.setReturnFormat('json')

endpoint support json: True

In [8]:
# testje SPARQLwrapper
# query gekopieerd van
sparql_ABR.setQuery("""
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rnce: <https://data.cultureelerfgoed.nl/id/rnce#>

SELECT ?aardewerkcategorie ?beginPeriode ?eindPeriode

WHERE { SERVICE <https://digitaalerfgoed.poolparty.biz/PoolParty/sparql/cb410a13-a6e8-4077-a02c-412a93714114> {
  <https://data.cultureelerfgoed.nl/term/id/abr/2/b402446a-0a00-4fee-a9cd-1a7f307d651e> skos:narrower+ ?cat_uri .
  ?cat_uri skos:prefLabel ?aardewerkcategorie ; rnce:hasBeginPeriodAbr/skos:prefLabel ?beginPeriode ; rnce:hasEndPeriodAbr/skos:prefLabel ?eindPeriode


} }
ORDER BY ?aardewerkcategorie
LIMIT 1
""")


try:
    test = sparql_ABR.queryAndConvert() # TODO returnt een byte object, met daarin HTML. Lijkt dus niet te kloppen, zou JSON moeten leveren. Onduidelijk of query niet klopt of setup van de sparqlwrapper niet klopt.
    for r in test["results"]["bindings"]:
        print(r)
except Exception as e:
    print(f"Exception\n {e}")
    print(type(test))
    print(test.decode('utf-8'))

Exception
 byte indices must be integers or slices, not str
<class 'bytes'>




























<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
  "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
      xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
      xmlns:skos="http://www.w3.org/2004/02/skos/core#"
      xmlns:skosxl="http://www.w3.org/2008/05/skos-xl#"
      xmlns:owl="http://www.w3.org/2002/07/owl#"
      xmlns:dc="http://purl.org/dc/elements/1.1/"
      xmlns:dcterms="http://purl.org/dc/terms/"
      xmlns:csw="http://semantic-web.at/ontologies/csw.owl#"
      xmlns:ctag="http://commontag.org/ns#"
      xmlns:opencyc="http://sw.opencyc.org/concept/"
      xmlns:freebase="http://rdf.freebase.com/ns/"
      xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
      xmlns:tags="http://www.holygoat.co.uk/owl/redwood/0.1/tags/"
      xmlns:foaf="http://xmlns.com/foaf/0.1/"
      xmlns:cyc="http://sw.cyc.com/concept/"
      xmlns:cycAnnot="http://sw.cyc.com/CycAnnotations_v1#"
      xmlns:dbpedia="http://dbpedia.org/resource/"
        >
<head>
  <title> - PoolParty Linked Data Server</title>
  <meta http-equiv="Cache-Control" content="no-store"/>
  <meta http-equiv="Pragma" content="no-cache"/>
  <meta http-equiv="Expires" content="0"/>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="keywords" content="taxonomy, thesaurus, controlled vocabulary, knowledge model, skos, semantic web, linked data, open data, rdf, download, trix, trig, poolparty"/>
  <link rel="icon" href="/PoolParty/OpenConfigPathResourceProvider/frontendroot?fileName=custom/images/favicon.ico" type="image/x-icon" />
  <link rel="stylesheet" href="/PoolParty/OpenConfigPathResourceProvider/frontendroot?fileName=custom/css/style.css" type="text/css" />
  <script type="text/javascript" src="/PoolParty/OpenConfigPathResourceProvider/frontendroot?fileName=custom/js/jquery-1.6.4.min.js"></script>
  <script type="text/javascript" src="/PoolParty/OpenConfigPathResourceProvider/frontendroot?fileName=custom/js/jquery.cookie.js"></script>
  <script type="text/javascript" src="/PoolParty/OpenConfigPathResourceProvider/frontendroot?fileName=custom/js/script.js"></script>
  <script type="text/javascript">
<!--
    var projectView = "/term/id/abr/2";
    var sparqlEndpointUrl = "https://data.cultureelerfgoed.nl/PoolParty/sparql/term/id/abr/2";
    var viewMore = [];
    var viewLess = [];
    var phone = [];
    var infoBoxText = [];
    var languages = ["nl"];
  //-->
  </script>

  <link rel="stylesheet" type="text/css" href="/PoolParty/lib/yui-2.9.0/build/autocomplete/assets/skins/sam/autocomplete.css" />
  <script type="text/javascript" src="/PoolParty/lib/yui-2.9.0/build/yahoo/yahoo-min.js"></script>
  <script type="text/javascript" src="/PoolParty/lib/yui-2.9.0/build/event/event-min.js"></script>
  <script type="text/javascript" src="/PoolParty/lib/yui-2.9.0/build/yahoo-dom-event/yahoo-dom-event.js"></script>
  <script type="text/javascript" src="/PoolParty/lib/yui-2.9.0/build/connection/connection-min.js"></script>
  <script type="text/javascript" src="/PoolParty/lib/yui-2.9.0/build/datasource/datasource-min.js"></script>
  <script type="text/javascript" src="/PoolParty/lib/yui-2.9.0/build/autocomplete/autocomplete-min.js"></script>
  <script type="text/javascript" src="/PoolParty/OpenConfigPathResourceProvider/frontendroot?fileName=custom/js/RdfAutoCompleteBuilder.js"></script>
  <script type="text/javascript">
  <!--
    var autocompleteNoResultsInfoBox = "NoResultsInfoBox";

    var PPP = new Object();
    PPP.infoBoxText = new Array();
    PPP.autocompleteLanguage = "nl";
    PPP.useLucene = "false";
    PPP.AC = new PoolPartyAutoComplete({"useLucene":PPP.useLucene,"id":"PPPAutoCompleteBuilder", "servletPath":"/PoolParty/HTMLFrontEndAC"});
    YAHOO.util.Event.onDOMReady(function() {
      try {
        PPP.AC.setDynamicDefaultAutoComplete("SearchAutoCompleteInput","SearchAutoCompleteOutput");
        PPP.AC.oDynamicAutoComplete.maxResultsDisplayed = 10;
        PPP.AC.oDynamicAutoComplete.useShadow = false;
        PPP.AC.oDynamicAutoComplete.autoHighlight = true;
        PPP.AC.oDynamicAutoComplete.typeAhead = true;
        PPP.AC.oDynamicAutoComplete.itemSelectEvent.unsubscribeAll();
        PPP.AC.oDynamicAutoComplete.itemSelectEvent.subscribe(function(sType, aArgs) {
          document.location.href=(aArgs[2][0]);
        });
        initLang();

        var replacements = new Object();
        replacements.ö = "(Ö|ö)";
        replacements.ä = "(Ä|ä)";
        replacements.ü = "(Ü|ü)";

        var toLowerCase = function (sText) {
          sText = (decodeURI(sText)).toLowerCase();
          for(umlaut in replacements){
            if(typeof replacements[umlaut] !== "function"){
              var regex = new RegExp( umlaut, "g" )
              sText = sText.replace( regex, replacements[umlaut] );
            }
          }
          return sText;
        };

        PPP.AC.oDynamicAutoComplete.generateRequest = function(sQuery) {
          var Q = toLowerCase(sQuery);
          return "lang="+PPP.autocompleteLanguage+"&query=" + Q +"&useLucene="+PPP.AC.useLucene+"&RepositoryID=1bfbc515-5bee-4c49-86aa-fb03c8ee3667";
        };
        PPP.AC.oDynamicAutoComplete.handleResponse = function(sQuery, oResponse, oPayload) {
          var aResults = oResponse.results;
          var elInput = this.getInputEl();
          var elInfoBox = document.getElementById(autocompleteNoResultsInfoBox);

          if (aResults.length > 0) {
            elInput.style.backgroundColor = "";
            elInfoBox.style.display = "none";

            var aListStart = new Array(),
              aListMiddle = new Array(),
              aListRest = new Array();

            var Q = toLowerCase(oPayload.query),
              start = new RegExp("^" + Q, "i"),
              middle = new RegExp(Q, "i");

            for (var i = 0, len = aResults.length; i < len; i++) {
              var oResult = aResults[i];
              if (start.test(oResult.label[0])) {
                aListStart.push(oResult);
              } else if (middle.test(oResult.label[0])) {
                aListMiddle.push(oResult);
              } else {
                aListRest.push(oResult);
              }
            }
            oResponse.results = aListStart.concat(aListMiddle.concat(aListRest));
          } else {
            elInput.style.backgroundColor = "#FFCCCC";
            if (PPP.infoBoxText[PPP.autocompleteLanguage].length > 0) {
              elInfoBox.innerHTML = PPP.infoBoxText[PPP.autocompleteLanguage];
              elInfoBox.style.display = "block";
            }
          }

          this._populateList(sQuery, oResponse, oPayload);
        };
      }
      catch(e) {
        console.error(e);
      }
    });
  //-->
  </script>
</head>
<body class="resource">
  <div id="container">
    <div id="header">
      <div id="logo"><a href="http://www.poolparty.biz/"><img border="0" src="/PoolParty/OpenConfigPathResourceProvider/frontendroot?fileName=custom/images/pp_logo.jpg" alt="PoolParty Linked Data Server" /></a></div>
      <div id="SearchContainer">
        <div id="ACcont">
            <input autocomplete="off" class="yui-ac-input" id="SearchAutoCompleteInput" type="text" title=""/>
            <div class="yui-ac-container" id="SearchAutoCompleteOutput"></div>
        </div>
        <div id="NoResultsInfoBox"></div>
      </div>
      <a class="sparqllink" href="https://data.cultureelerfgoed.nl/PoolParty/sparql/term/id/abr/2">SPARQL</a>
    </div>

    <div id="index-bar">
  <ul>
    <li><a>A</a></li>
    <li><a>B</a></li>
    <li><a>C</a></li>
    <li><a>D</a></li>
    <li><a>E</a></li>
    <li><a>F</a></li>
    <li><a>G</a></li>
    <li><a>H</a></li>
    <li><a>I</a></li>
    <li><a>J</a></li>
    <li><a>K</a></li>
    <li><a>L</a></li>
    <li><a>M</a></li>
    <li><a>N</a></li>
    <li><a>O</a></li>
    <li><a>P</a></li>
    <li><a>Q</a></li>
    <li><a>R</a></li>
    <li><a>S</a></li>
    <li><a>T</a></li>
    <li><a>U</a></li>
    <li><a>V</a></li>
    <li><a>W</a></li>
    <li><a>X</a></li>
    <li><a>Y</a></li>
    <li><a>Z</a></li>
  </ul>
    </div>

    <div id="breadcrumb">
      <ul>
        <li><a href="/">PoolParty Linked Data Server</a></li>
        <li class="separator"></li>
        <li><a href="/term/id/abr/2">Archeologisch Basis Register versie 2</a></li>
      </ul>
    </div>

    <div id="languageSelector">
      <select name="language" onchange="changeLang(this)">
        <option value="nl"  selected="selected" >nl</option>
      </select>
    </div>

    <div class="content_wrapper">



     <div id="tabs">
      <ul>
        <li  class="active" ><a href="https://data.cultureelerfgoed.nl/term/id/abr/2/b402446a-0a00-4fee-a9cd-1a7f307d651e">HTML</a></li>
        <li ><a href="https://data.cultureelerfgoed.nl/term/id/abr/2/b402446a-0a00-4fee-a9cd-1a7f307d651e.visual">Visual</a></li>
      </ul>
    </div>

    <div id="main_content">

<div id="resources">
  <div id="nl"  class="resource nl" about="https://data.cultureelerfgoed.nl/term/id/abr/2/b402446a-0a00-4fee-a9cd-1a7f307d651e">
        <h1 class="title"><a href="https://data.cultureelerfgoed.nl/term/id/abr/2/b402446a-0a00-4fee-a9cd-1a7f307d651e">Archeologisch Basis Register</a></h1>
        <a href="https://data.cultureelerfgoed.nl/term/id/abr/2/b402446a-0a00-4fee-a9cd-1a7f307d651e">https://data.cultureelerfgoed.nl/term/id/abr/2/b402446a-0a00-4fee-a9cd-1a7f307d651e</a>
  <ul class="default">
      <li class="box">
        <h2><a href="http://purl.org/dc/terms/subject">Subject</a></h2>
	    <ul><li>ABR</li></ul>
      </li>
      <li class="box">
        <h2><a href="http://purl.org/dc/terms/subject">Subject</a></h2>
	    <ul><li>Archis</li></ul>
      </li>
  <li class="box">
     <h2><a href="http://www.w3.org/2004/02/skos/core#hasTopConcept">has top concept</a></h2>
         <ul>

                    <li><a href="https://data.cultureelerfgoed.nl/term/id/abr/2/6b152e0a-34da-4309-bd3e-c7140ca58640">aardewerkcategorie</a></li>

                    <li><a href="https://data.cultureelerfgoed.nl/term/id/abr/2/22cbb070-6542-48f0-8afe-7d98d398cc0b">artefacten</a></li>

                    <li><a href="https://data.cultureelerfgoed.nl/term/id/abr/2/f9f5fea8-8e07-4fca-bfa6-8bd092d8586b">baksels</a></li>

                    <li><a href="https://data.cultureelerfgoed.nl/term/id/abr/2/2bd9cf3b-c356-43f3-866e-742e0e508b3a">bodemgebruik</a></li>

                    <li><a href="https://data.cultureelerfgoed.nl/term/id/abr/2/d5a21eab-a53b-41c9-b901-8e6390f63535">brontypen</a></li>

                    <li><a href="https://data.cultureelerfgoed.nl/term/id/abr/2/e9546020-4b28-4819-b0c2-29e7c864c5c0">complextypen</a></li>

                    <li><a href="https://data.cultureelerfgoed.nl/term/id/abr/2/166c0cd8-0a6c-4d1d-926d-b1f65e9d9e39">coördinatenstelsels</a></li>

                    <li><a href="https://data.cultureelerfgoed.nl/term/id/abr/2/e910056d-4b9b-4212-b979-fada951ef8e8">culturen</a></li>

                    <li><a href="https://data.cultureelerfgoed.nl/term/id/abr/2/3f649428-b422-4a64-ab6b-9ba3ae4f3c4d">dateringsmethoden</a></li>

                    <li><a href="https://data.cultureelerfgoed.nl/term/id/abr/2/e401ee4d-44c1-45e2-8d59-798a86662f2a">deventer objectcodes</a></li>

                    <li><a href="https://data.cultureelerfgoed.nl/term/id/abr/2/5b1ce76a-fa80-4d3a-b8e3-8fe1c0d547db">deventer warecodes</a></li>

                    <li><a href="https://data.cultureelerfgoed.nl/term/id/abr/2/82638dc4-8095-4c54-a7ff-49ac32ad5361">geomorfologie</a></li>

                    <li><a href="https://data.cultureelerfgoed.nl/term/id/abr/2/2dcb88e1-e777-4cff-babc-d97485b42b10">materialen</a></li>

                    <li><a href="https://data.cultureelerfgoed.nl/term/id/abr/2/111a08d1-995a-43e2-9213-5fecd8f3d00f">objecttype maritiem</a></li>

                    <li><a href="https://data.cultureelerfgoed.nl/term/id/abr/2/9b688754-1315-484b-9c89-8817e87c1e84">periodes</a></li>

                    <li><a href="https://data.cultureelerfgoed.nl/term/id/abr/2/7a99aaba-c1e7-49a4-9dd8-d295dbcc870e">rapporten</a></li>

                    <li><a href="https://data.cultureelerfgoed.nl/term/id/abr/2/08135028-b53e-469a-a44b-c7960f815503">sporen</a></li>

                    <li><a href="https://data.cultureelerfgoed.nl/term/id/abr/2/afa1ba38-b579-405a-93eb-0ea1e93cfba1">stromingen</a></li>

                    <li><a href="https://data.cultureelerfgoed.nl/term/id/abr/2/b0464f59-a883-441e-b819-84a47857cc09">structuren</a></li>

                    <li><a href="https://data.cultureelerfgoed.nl/term/id/abr/2/deb35fe7-d874-4c3d-be52-8ab81153c0e6">textuur</a></li>

                    <li><a href="https://data.cultureelerfgoed.nl/term/id/abr/2/554ca1ec-3ed8-42d3-ae4b-47bcb848b238">verwervingswijzen</a></li>

                    <li><a href="https://data.cultureelerfgoed.nl/term/id/abr/2/92210070-7f3c-4465-830e-005dc2b73ee8">verzamelwijzen en monstertypes</a></li>
         </ul>
  </li>

      <li class="box">
	<h2><a href="http://purl.org/dc/terms/creator">http://purl.org/dc/terms/creator</a></h2>
	<ul><li>Rijksdienst voor het Cultureel Erfgoed</li></ul>
      </li>
      <li class="box">
	<h2><a href="http://purl.org/dc/terms/publisher">Publisher (Organisation)</a></h2>
        <ul><li>Rijksdienst voor het Cultureel Erfgoed</li></ul>
      </li>
  </ul>   </div> </div>

    </div>  <!-- main_content -->
    </div>  <!-- content_wrapper -->
    <div id="footer">
      <ul id="nav_bottom">
        <li><a href="http://poolparty.biz/company" target="pp_contact">contact</a></li>
        <li>|</li>
        <li><a href="https://help.poolparty.biz/display/doc/Linked+Data+and+Schema+Publishing+with+PoolParty" target="pp_about">about</a></li>
        <li>|</li>
        <li><a href="http://www.w3.org/2004/02/skos/" target="pp_skos">skos</a></li>
      </ul>
      <p id="poolparty">
        Powered by <a href="http://poolparty.biz"><img class="pplogo" border="0" src="/PoolParty/OpenConfigPathResourceProvider/frontendroot?fileName=custom/images/pp_logo.png" alt="PoolParty Server" /></a>
	</p>
    </div>
  </div>    <!-- container -->
</body>
</html>

C:\Users\t.vandenberg\Documents\DNA-NL\RCE_DNANL_B-DK_use_cases_testen\notebooks\.venv\Lib\site-packages\SPARQLWrapper\Wrapper.py:1215: RuntimeWarning: unknown response content type 'text/html' returning raw response...
  warnings.warn(

In [9]:
print(b"hello")

b'hello'

## Duckdb setup (niet relevant voor non-programmeerder)
duckdb is een databasemanagementsoftware vergelijkbaar met PostGRES en MySQL. Het gebruikt SQL queries om met de data te interacteren. In dit notebook gaat dit volledig lokaal en in het werkgeheugen van de computer, anders dan in het DAP, echter, de queries die moeten worden uitgevoerd voor het verbeteren van de data zijn grotendeels hetzelfde.

### Laad de Spatial Extension
https://duckdb.org/docs/current/core_extensions/spatial/overview

In [10]:
duckdb.sql("""
           INSTALL spatial;
           LOAD spatial;
           """)

### laad database (schema's) in de bronzen laag

In [11]:
duckdb.sql("""
           CREATE SCHEMA IF NOT EXISTS brons_archeologische_complexen;
           """)

### laad parquet files als een tabellen in de bronzen laag

In [12]:
duckdb.sql("""
           CREATE TABLE IF NOT EXISTS brons_archeologische_complexen.def_complexen_v8 AS
           FROM read_parquet('./data/brons/def_complexen_v8/def_complexen_v8.parquet');
           """)

## Maak test dataset

In [13]:
duckdb.sql("""DROP TABLE IF EXISTS test.test""")
duckdb.sql("""CREATE SCHEMA IF NOT EXISTS test;""")
duckdb.sql("""CREATE TABLE IF NOT EXISTS test.test (test_eenheid_grootheid VARCHAR);""")
duckdb.sql("""INSERT INTO test.test (test_eenheid_grootheid) VALUES ('1cm'), ('1 cm'), ('F23B'), ('23FB'), ('1cm1'), ('cm1');""")
df = duckdb.sql("""SELECT * FROM test.test;""").fetchdf()
df

  test_eenheid_grootheid
0                    1cm
1                   1 cm
2                   F23B
3                   23FB
4                   1cm1
5                    cm1

## Algemene omschrijvingen

Hier wordt de data in het algemeen uiteengezet. Dit zijn geen testen, maar er valt veel informatie terug te lezen over de opzet van de dataset.

### Omschrijf de eigenschappen van de kolommen.

In [14]:
df = duckdb.sql("""
        DESCRIBE brons_archeologische_complexen.def_complexen_v8;
        """).fetchdf()
df

   column_name             column_type null   key default extra
0   complex_id                  DOUBLE  YES  None    None  None
1   terreinnum                  DOUBLE  YES  None    None  None
2   rijksmonum                  DOUBLE  YES  None    None  None
3          cma                 VARCHAR  YES  None    None  None
4   cma_volgnr                 VARCHAR  YES  None    None  None
5   cpx_monito                  BIGINT  YES  None    None  None
6     cpx_jaar                 VARCHAR  YES  None    None  None
7   cpx_code_b                 VARCHAR  YES  None    None  None
8   cpx_code_o                 VARCHAR  YES  None    None  None
9   cpx_code_n                 VARCHAR  YES  None    None  None
10   cpx_begin                 VARCHAR  YES  None    None  None
11  cpx_eind_p                 VARCHAR  YES  None    None  None
12  cpx_zichtb                 VARCHAR  YES  None    None  None
13  cpx_beschr                 VARCHAR  YES  None    None  None
14   cpx_kwets                 VARCHAR  YES  None    None  None
15  cpx_restau                 VARCHAR  YES  None    None  None
16  cpx_consol                 VARCHAR  YES  None    None  None
17  cpx_diepte                  DOUBLE  YES  None    None  None
18  cpx_diep00                  DOUBLE  YES  None    None  None
19  cpx_x_coor                  DOUBLE  YES  None    None  None
20  cpx_y_coor                  DOUBLE  YES  None    None  None
21  cpx_opmerk                 VARCHAR  YES  None    None  None
22    geometry  GEOMETRY('EPSG:28992')  YES  None    None  None

### Omschrijf de eigenschappen van de waarden in de kolommen.
Let op: veel van deze omschrijvingen zijn niet erg behulpzaam voor tekstkolommen. Dit zijn: min, max, avg, std, q25, q50 en q75.

In [15]:
duckdb.sql("""
        SUMMARIZE brons_archeologische_complexen.def_complexen_v8;""").fetchdf()

,column_name,column_type,min,max,approx_unique,avg,std,q25,q50,q75,count,null_percentage
0,complex_id,DOUBLE,20.0,50999.0,4482,14936.711100339311,20197.506587843258,1173.1558922558922,2332.3364877133054,16567.20975938507,4126,0.00
1,terreinnum,DOUBLE,42.0,20016.0,2300,2786.5399903053803,3964.6532419246237,671.9497071688043,1387.452600800246,1610.1471065440778,4126,0.00
2,rijksmonum,DOUBLE,31550.0,532469.0,1877,119046.30392632089,167622.54516092004,45475.557098765436,45788.64903107646,46174.0,4126,0.00
3,cma,VARCHAR,02G-026,geen CMA-nummer,1356,NaN,NaN,NaN,NaN,NaN,4126,6.62
4,cma_volgnr,VARCHAR,12A-001-01,?,1645,NaN,NaN,NaN,NaN,NaN,4126,55.84
5,cpx_monito,BIGINT,0,5220,3415,1746.8800290838585,1241.7678228908678,718,1538,2801,4126,0.00
6,cpx_jaar,VARCHAR,20150101000000.000,20170912000000.000,4,NaN,NaN,NaN,NaN,NaN,4126,92.46
7,cpx_code_b,VARCHAR,(Ring)walburg,weg,62,NaN,NaN,NaN,NaN,NaN,4126,0.00
8,cpx_code_o,VARCHAR,EGMW,VX,64,NaN,NaN,NaN,NaN,NaN,4126,0.51
9,cpx_code_n,VARCHAR,APVV,nederzettingsresten Swifterbantcultuur,76,NaN,NaN,NaN,NaN,NaN,4126,0.48
10,cpx_begin,VARCHAR,Bronstijd,midden Neolithicum B,69,NaN,NaN,NaN,NaN,NaN,4126,0.02
11,cpx_eind_p,VARCHAR,Bronstijd,late Middeleeuwen B,67,NaN,NaN,NaN,NaN,NaN,4126,0.02
12,cpx_zichtb,VARCHAR,ja,onbekend,4,NaN,NaN,NaN,NaN,NaN,4126,0.56
13,cpx_beschr,VARCHAR,(geegaliseerde) grafheuvel,wordt nader ingevuld,591,NaN,NaN,NaN,NaN,NaN,4126,8.43
14,cpx_kwets,VARCHAR,ja,onbekend,2,NaN,NaN,NaN,NaN,NaN,4126,0.95
15,cpx_restau,VARCHAR,ja,opgegraven en gerestaureerd,5,NaN,NaN,NaN,NaN,NaN,4126,99.47
16,cpx_consol,VARCHAR,ja,nee,2,NaN,NaN,NaN,NaN,NaN,4126,99.85
17,cpx_diepte,DOUBLE,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,4126,0.00
18,cpx_diep00,DOUBLE,-0.6,2.5,3,0.00046049442559379543,0.04002764214765763,0.0,0.0,0.0,4126,0.00
19,cpx_x_coor,DOUBLE,0.0,267570.31305,3583,184250.2051936869,49403.845858317465,169781.76239830648,178277.32686953613,226715.8139065425,4126,0.00
20,cpx_y_coor,DOUBLE,0.0,825146.7239,3246,474614.7347112509,85131.10132847646,434993.39365415316,477536.53460594435,536970.1115447021,4126,0.00
21,cpx_opmerk,VARCHAR,"(Groep 14B, RAAP-cat.nr. 2, RAAP-objectnr. 5G-...",zichtbaar bij laag water,38,NaN,NaN,NaN,NaN,NaN,4126,98.93
22,geometry,GEOMETRY('EPSG:28992'),"POLYGON Z ((152125.39995 459013.30007500004 0,...",MULTIPOLYGON Z (((145430.499925 524967.600025 ...,3070,NaN,NaN,NaN,NaN,NaN,4126,0.00

# Pas de datakwaliteits richtlijnen toe

In [16]:
# algemene variabelen
table =  "brons_archeologische_complexen.def_complexen_v8"
schema = "brons_archeologische_complexen"
table_name = 'def_complexen_v8'
dk_dimensies_voldaan = 0

## Dimensie 1: referentiële integriteit en unieke identificatie


- Vraag: Welke kolom bevat de primary key/ID?
    - Test A: Alle IDs in de primary key kolom zijn uniek.
    - Test B: Er zijn geen lege waarden in de primary key kolom.
    - Test C: In de databasestructuur is aangegeven dat de primary key kolom uniek moet zijn.
    - Test D: In de databasestructuur is aangegeven dat de primary key geen lege waarden mag bevatten.
    - Test E: In de databasestructuur is aangegeven dat de kolom een primary key is.
- Vraag: Welke kolom(men) bevat(ten) foreign key(s)?
    - Vraag: Naar welke dataset verwijst/verwijzen deze foreign key(s)?
        - Test F: Het is bekend van elke foreign key waar deze naar verwijst
    - Vraag: Is er een losse kolom voor elke foreign key? (note Thya: dit zou ik graag automatiseren en in een test veranderen, maar ik zie nog niet goed hoe.)
        - Test G: De foreign key(s) kom(t/en) overeen met een primary key uit de dataset waar deze naar verwijst.
    - Hebben alle foreign keys een eigen kolom?

In [17]:
test_resultaten_dim1 = []

#### Vraag: Welke kolom bevat de primary key?

In [18]:
primary_id_kolom = "complex_id"
print(f"de volgende kolom bevat de primary key: {primary_id_kolom}")

de volgende kolom bevat de primary key: complex_id

#### Test A

In [19]:
pk_is_unique = duckdb.sql(f"""
SELECT(
    SELECT
        COUNT()
    FROM (
        SELECT
            DISTINCT {primary_id_kolom}
        FROM {table}
    )
) == (
    SELECT
        COUNT()
    FROM {table}
)
AS unique_identifier;
""").fetchone()[0]
print(f"Test A :Alle IDs in de primary ID kolom zijn uniek: {pk_is_unique}")
test_resultaten_dim1.append(pk_is_unique)

Test A :Alle IDs in de primary ID kolom zijn uniek: True

#### Test B

In [20]:
pk_is_not_null = duckdb.sql(f"""
SELECT (
    SELECT
        COUNT()
    FROM {table}
    WHERE {primary_id_kolom} IS NULL
    ) = 0
AS null_identifier;
""").fetchone()[0]
print(f"Test B: Er zijn geen lege waarden in de primary id kolom: {pk_is_not_null}")
test_resultaten_dim1.append(pk_is_not_null)

Test B: Er zijn geen lege waarden in de primary id kolom: True

#### Test C

In [21]:
# Deze check heeft op dit punt geen zin, want parquet files hebben geen primary keys

pk_schema_unique = duckdb.sql(f"""
SELECT
    CASE WHEN EXISTS(
        SELECT
            tc.constraint_type
        FROM
            information_schema.table_constraints tc
        JOIN
            information_schema.key_column_usage kcu
            ON tc.constraint_name = kcu.constraint_name
            AND tc.table_schema = kcu.table_schema
            AND tc.table_name = kcu.table_name
        WHERE
            tc.table_schema = '{schema}'
            AND tc.table_name = '{table_name}'
            AND kcu.column_name = '{primary_id_kolom}'
            AND tc.constraint_type = 'UNIQUE')
    THEN True
    ELSE False
    END
AS has_unique_constraint;
""").fetchone()[0]
print(f"Test C: In de databasestructuur is aangegeven dat de primary key kolom unique moet zijn: {pk_schema_unique}")
test_resultaten_dim1.append(pk_schema_unique)

Test C: In de databasestructuur is aangegeven dat de primary key kolom unique moet zijn: False

#### Test D

In [22]:
pk_schema_not_null = duckdb.sql(f"""
SELECT(
    SELECT is_nullable FROM information_schema.columns
        WHERE table_schema = '{schema}' AND table_name = '{table_name}' AND column_name = '{primary_id_kolom}'
    ) = 'NO' as not_nullable;""").fetchone()[0]
print(f"Test D: In de databasestructuur is aangegeven dat de primary key kolom niet null mag zijn: {pk_schema_not_null}")
test_resultaten_dim1.append(pk_schema_not_null)

Test D: In de databasestructuur is aangegeven dat de primary key kolom niet null mag zijn: False

#### Test E

In [23]:
pk_schema_exists = duckdb.sql(f"""
SELECT
    CASE WHEN EXISTS (
        SELECT
            1
        FROM
            information_schema.table_constraints tc
        JOIN
            information_schema.key_column_usage kcu
            ON tc.constraint_name = kcu.constraint_name
            AND tc.table_schema = kcu.table_schema
            AND tc.table_name = kcu.table_name
        WHERE
            tc.table_schema = 'schema1'
            AND tc.table_name = 'table1'
            AND kcu.column_name = 'column1'
            AND tc.constraint_type = 'PRIMARY KEY'
    ) THEN TRUE
    ELSE FALSE
    END
AS is_primary_key;
""").fetchone()[0]
print(f"Test E: In de databasestructuur is aangegeven dat de primary key een primary key is: {pk_schema_exists}")
test_resultaten_dim1.append(pk_schema_exists)

Test E: In de databasestructuur is aangegeven dat de primary key een primary key is: False

#### Vragen: Welke kolom(men) bevat(ten) foreign key(s) ; Naar welke dataset verwijst/verwijzen deze foreign key(s)?
handmatig ingevoerd op basis van domeinkennis, dit is niet met code te achterhalen.
Let op: nog geen code geschreven om ook een kolom waar meerdere gemixte foreign keys in staan te checken, omdat dit voor deze dataset niet nodig is. Komt later. #TODO

In [24]:
# in de eerste waarde ([0]) van de lijst staat naar welke dataset/database verwezen wordt, in de tweede [1] staat het schema van hoe deze op dit moment is ingeladen in brons, in de derde [2] de tabelnaam in brons, en de vierde [3] de kolomnaam van de primary key van die dataset en de vijfde [4] de opgeslagen parquet file óf de waarde None als het niet om een vindbare dataset gaat.
dict_foreign_keys = {
    "terreinnum": ["DEF_terreinen_v5", "brons_archeologische_terreinen", "def_terreinen_v5",  "terreinnum", r"./data/brons/def_terreinen_v5/def_terreinen_v5.parquet"],
    "rijksmonum": ["rijksmonumentenregister", "brons_rijksmonumentenregister", "tblTEXT_OBJECT", "TXO_TEXT_KEY", r"./data/brons/rijksmonumentenregister/tblTEXT_OBJECT.parquet"],
    "cma":["Centraal_monumenten_archief", None, None, None, None], #zit in Proza, niet te testen. Dit is een gedigitaliseerd/gscand papieren archief. Geen verantwoordelijke, maar vraag Guide Mauro
    "cma_volgnr": ["Centraal_monumenten_archief", None, None, None, None], # zit in Proza, niet te testen
    "cpx_monito": [None,None, None, None, None] # Herkomst onbekend. In (verhouderde) data dictionary staat Unieke identifier RCE monitor, maar welke? Niet de BAAC nulmonitor en niet de huidige monitor.
}
for item in dict_foreign_keys:
    if dict_foreign_keys[item][0]:
        if dict_foreign_keys[item][4]:
            print(f"kolom {item} verwijst naar de primary key van {dict_foreign_keys[item][0]}, deze staat in kolom {dict_foreign_keys[item][3]} van {dict_foreign_keys[item][1]}.{dict_foreign_keys[item][2]}")
        else:
            print(f"kolom {item} verwijst naar een key van {dict_foreign_keys[item][0]}, deze dataset is niet ingeladen in de omgeving.")
    else:
        print(f"kolom {item} verwijst naar een onbekende dataset.")

kolom terreinnum verwijst naar de primary key van DEF_terreinen_v5, deze staat in kolom terreinnum van brons_archeologische_terreinen.def_terreinen_v5
kolom rijksmonum verwijst naar de primary key van rijksmonumentenregister, deze staat in kolom TXO_TEXT_KEY van brons_rijksmonumentenregister.tblTEXT_OBJECT
kolom cma verwijst naar een key van Centraal_monumenten_archief, deze dataset is niet ingeladen in de omgeving.
kolom cma_volgnr verwijst naar een key van Centraal_monumenten_archief, deze dataset is niet ingeladen in de omgeving.
kolom cpx_monito verwijst naar een onbekende dataset.

#### Test F

In [25]:
fk_ref_known = True

for item in dict_foreign_keys:
    if not dict_foreign_keys[item][0]:
        fk_ref_known = False
print(f"Test F: Het is voor elke foreign key bekend welke dataset deze naar refereert: {fk_ref_known}")
test_resultaten_dim1.append(fk_ref_known)

Test F: Het is voor elke foreign key bekend welke dataset deze naar refereert: False

#### Test G

laad de benodigde datasets in zodat er een vergelijking gemaakt kan worden

In [26]:
for item in dict_foreign_keys:
    if dict_foreign_keys[item][4]:
        duckdb.sql(f"""
                   CREATE SCHEMA IF NOT EXISTS {dict_foreign_keys[item][1]};
                   """)
        duckdb.sql(f"""
                   CREATE TABLE IF NOT EXISTS {dict_foreign_keys[item][1]}.{dict_foreign_keys[item][2]} AS
                   FROM read_parquet('{dict_foreign_keys[item][4]}');
                   """)
    else:
        print(f"LET OP!: dataset {dict_foreign_keys[item][0]} voor foreign key {item} wordt niet gecheckt.")

LET OP!: dataset Centraal_monumenten_archief voor foreign key cma wordt niet gecheckt.
LET OP!: dataset Centraal_monumenten_archief voor foreign key cma_volgnr wordt niet gecheckt.
LET OP!: dataset None voor foreign key cpx_monito wordt niet gecheckt.

In [27]:
# test hier of het inladen gelukt is:
# duckdb.sql(f"""DESCRIBE brons_archeologische_terreinen.def_terreinen_v5;""")
# duckdb.sql(f"""DESCRIBE brons_rijksmonumentenregister.tblTEXT_OBJECT;""")

In [28]:
fk_all_match = True
for item in dict_foreign_keys:
    if dict_foreign_keys[item][4]:
        val = duckdb.sql(f"""
        SELECT
            LIST_HAS_ALL((
                SELECT
                    LIST({dict_foreign_keys[item][3]})
                FROM {dict_foreign_keys[item][1]}.{dict_foreign_keys[item][2]}),
                (SELECT
                    LIST({item})
                FROM {table})
        );
        """).fetchone()[0]
        print(f"alle waarden in de foreign key kolom {item} komen voor in de kolom {dict_foreign_keys[item][3]} van {dict_foreign_keys[item][1]}.{dict_foreign_keys[item][2]}: {val}")
        if not val:
            fk_all_match = False
print(f"De foreign key(s) kom(t/en) overeen met een primary key(s) uit de dataset waar deze naar verwijst/verwijzen: {fk_all_match}")
test_resultaten_dim1.append(fk_all_match)

alle waarden in de foreign key kolom terreinnum komen voor in de kolom terreinnum van brons_archeologische_terreinen.def_terreinen_v5: True
alle waarden in de foreign key kolom rijksmonum komen voor in de kolom TXO_TEXT_KEY van brons_rijksmonumentenregister.tblTEXT_OBJECT: False
De foreign key(s) kom(t/en) overeen met een primary key(s) uit de dataset waar deze naar verwijst/verwijzen: False

#### Resultaten dimensie 1

In [29]:
aantal_testen_succes_dim1 = 0

for test in test_resultaten_dim1:
    if test:
        aantal_testen_succes_dim1 += 1

if len(test_resultaten_dim1) == aantal_testen_succes_dim1:
    print(f"Er zijn {len(test_resultaten_dim1)} tests uitgevoerd voor dimensie 1. Daarvan is/zijn aan {aantal_testen_succes_dim1} test(en) voldaan. Dat betekent dat aan datakwaliteitsdimensie 1 in zijn geheel is voldaan")
    dk_dimensies_voldaan +=1
else:
    print(f"Er zijn {len(test_resultaten_dim1)} tests uitgevoerd voor dimensie 1. Daarvan is/zijn aan {aantal_testen_succes_dim1} test(en) voldaan. Dat betekent dat aan datakwaliteitsdimensie 1 NIET in zijn geheel is voldaan.")

Er zijn 7 tests uitgevoerd voor dimensie 1. Daarvan is/zijn aan 2 test(en) voldaan. Dat betekent dat aan datakwaliteitsdimensie 1 NIET in zijn geheel is voldaan.

## Dimensie 2: Structurele consistentie
* Vraag: Is het datatype voor elke kolom logisch voor de informatie die in die kolom staat?
    * Test A: Er zijn geen kolommen die volledig uit data van een ander type dan het aangegeven type bestaan.
        * A.1 floats die integers zouden kunnen zijn
        * A.2 integers die booleans zouden kunnen zijn
        * A.3 tekst die numeric (float of integer) zouden kunnen zijn?
* Vraag: Bevat elke kolom maar 1 datatype?
    * Test B: Er zijn geen tekstkolommen die data van een ander type bevatten
* Vraag: Bevat elke kolom maar 1 stuk informatie?
    * Test C: Er zijn geen tekstkolommen die bestaan uit een combinatie van grootheden met eenheden.
    * Test D: Alle kolommen hebben een andere naam.
    * Test E: Er zijn geen kolommen met volledig gedupliceerde informatie.
* Vraag: Is het gebruik van onbekende waarden consistent?
    * Test F: Er is maximaal 1 waarde voor informatie die niet is ingevuld (1 van: NULL, NA, n/a, None, "")
    * Test G: Er is maximaal 1 waarde per datatype voor informatie die onbekend is. (bijvoorbeeld ?, -, "onbekend", 9999, 0000, 01-01-1901)

In [30]:
# get all the datatypes to be tested
list_datatypes =[name for name, value in inspect.getmembers(duckdb.sqltypes)
    if not name.startswith("_")
]
print("de volgende datatypen zijn beschikbaar in duckdb")
list_datatypes

de volgende datatypen zijn beschikbaar in duckdb

['BIGINT',
 'BIT',
 'BLOB',
 'BOOLEAN',
 'DATE',
 'DOUBLE',
 'DuckDBPyType',
 'FLOAT',
 'HUGEINT',
 'INTEGER',
 'INTERVAL',
 'SMALLINT',
 'SQLNULL',
 'TIME',
 'TIMESTAMP',
 'TIMESTAMP_MS',
 'TIMESTAMP_NS',
 'TIMESTAMP_S',
 'TIMESTAMP_TZ',
 'TIME_NS',
 'TIME_TZ',
 'TINYINT',
 'UBIGINT',
 'UHUGEINT',
 'UINTEGER',
 'USMALLINT',
 'UTINYINT',
 'UUID',
 'VARCHAR',
 'VARIANT']

In [31]:

# remove unnecesary datatypes
print("De volgende datatypen worden gegroepeerd:")

# group datatypes that are tested in the same way
dict_datatypes = {
    'integer': ['BIGINT', 'HUGEINT','INTEGER','SMALLINT','TINYINT','UBIGINT','UHUGEINT','UINTEGER','USMALLINT','UTINYINT','UUID'],
    'float': ['DOUBLE','FLOAT'],
    'decimal': ['DECIMAL'],
    'datetime': ['DATE', 'TIMESTAMP', 'TIME', 'TIMESTAMP', 'TIMESTAMP_MS', 'TIMESTAMP_NS', 'TIMESTAMP_S', 'TIMESTAMP_TZ', 'TIME_NS', 'TIME_TZ'],
    'boolean': ['BOOLEAN'],
    'string': ['VARCHAR']

}
dict_datatypes

De volgende datatypen worden gegroepeerd:

{'integer': ['BIGINT',
  'HUGEINT',
  'INTEGER',
  'SMALLINT',
  'TINYINT',
  'UBIGINT',
  'UHUGEINT',
  'UINTEGER',
  'USMALLINT',
  'UTINYINT',
  'UUID'],
 'float': ['DOUBLE', 'FLOAT'],
 'decimal': ['DECIMAL'],
 'datetime': ['DATE',
  'TIMESTAMP',
  'TIME',
  'TIMESTAMP',
  'TIMESTAMP_MS',
  'TIMESTAMP_NS',
  'TIMESTAMP_S',
  'TIMESTAMP_TZ',
  'TIME_NS',
  'TIME_TZ'],
 'boolean': ['BOOLEAN'],
 'string': ['VARCHAR']}

#### Test A

In [32]:
datatype_all_match = True
for item in dict_datatypes:
    if item == 'integer':
        # check if integer may be a boolean
        for datatype in dict_datatypes[item]:
            list_of_cols = duckdb.sql(f"""
                                            SELECT column_name FROM (DESCRIBE {table}) WHERE column_type ==  '{datatype}'
                                            """).fetchall()
            for item in list_of_cols:
                integer_contains_bool = duckdb.sql(f"""
                SELECT
                    CASE WHEN
                        (SELECT
                            COUNT({item[0]})
                        FROM
                            {table}
                        WHERE {item[0]} == 0
                        OR {item[0]} == 1
                        )
                        ==
                        (SELECT COUNT({item[0]}) FROM {table})
                        THEN True
                        ELSE False
                        END;
                """).fetchone()[0]
                if integer_contains_bool:
                    print(f'column {item[0]} with datatype {datatype} contains only 1 and 0 and is likely a boolean. The datatype is likely wrong')
                    datatype_all_match = False
                else:
                    print(f'column {item[0]} with datatype {datatype} is likely of the correct type.')


    elif item == 'float':
        # check if floating numbers may actually be integers. Are there any non-0 decimal numbers?
        # if more than 50% of the numbers are like this, the data type may be mixed. #TODO is this the correct cut-off?
        for datatype in dict_datatypes[item]:
            # query checks if column with type exists and returns columns
            list_of_cols = duckdb.sql(f"""
                                            SELECT column_name FROM (DESCRIBE {table}) WHERE column_type ==  '{datatype}'
                                            """).fetchall()
            for item in list_of_cols:

                float_contains_integer = duckdb.sql(f"""
                SELECT
                    CASE WHEN (
                    (SELECT
                        COUNT({item[0]})
                    FROM {table}
                    WHERE ({item[0]} % 1) == 0
                    )
                    >
                    (SELECT 0.5* COUNT() FROM {table}))
                    THEN True
                    ELSE False
                    END;
                """).fetchone()[0]

                float_contains_only_int = duckdb.sql(f"""
                SELECT
                    CASE WHEN (
                    (SELECT
                        COUNT({item[0]})
                    FROM {table}
                    WHERE ({item[0]} % 1) == 0
                    )
                    ==
                    (SELECT COUNT() FROM {table}))
                    THEN True
                    ELSE False
                    END;
                """).fetchone()[0]
                if float_contains_integer:
                    if float_contains_only_int:
                        print(f'column {item[0]} with datatype {datatype} contains no values with decimal points. The datatype is likely wrong')
                        datatype_all_match = False
                    else:
                        print(f'WARNING: column {item[0]} with type {datatype} contains more than 50% values that could be INTEGERS, the datatype may be incorrect but the test is not considered failed')
                else:
                    print(f'column {item[0]} with type {datatype} contains less than 50% values that could be INTEGERS, the data type is likely correct')
    elif item == 'string':
        for datatype in dict_datatypes[item]:
            list_of_cols = duckdb.sql(f"""
                                            SELECT column_name FROM (DESCRIBE {table}) WHERE column_type ==  '{datatype}'
                                            """).fetchall()
            for item in list_of_cols:
                # check if some strings contain only numbers
                string_contains_only_numeric = duckdb.sql(f"""
                SELECT
                    CASE WHEN (
                        SELECT
                            COUNT({item[0]})
                        FROM
                            {table}
                        WHERE
                            regexp_full_match({item[0]}, '[^0-9]')
                    )
                    >
                    (SELECT
                        0.5 * COUNT()
                    FROM
                        {table})
                    THEN True
                    ELSE False
                    END;
                """).fetchone()[0]

                if string_contains_only_numeric:
                        print(f'column {item[0]} with datatype {datatype} contains only values that consists of numbers. The datatype is likely wrong')
                        datatype_all_match = False
                else:
                    print(f'column {item[0]} with datatype {datatype} is likely of the correct type')
    else:
        print(f"datatype {item} is untested")

print(f"Test A: Er zijn geen kolommen die volledig uit data van een ander type dan het aangegeven type bestaan: {fk_ref_known}")

column cpx_monito with datatype BIGINT is likely of the correct type.
column complex_id with datatype DOUBLE contains no values with decimal points. The datatype is likely wrong
column terreinnum with datatype DOUBLE contains no values with decimal points. The datatype is likely wrong
column rijksmonum with datatype DOUBLE contains no values with decimal points. The datatype is likely wrong
column cpx_diepte with datatype DOUBLE contains no values with decimal points. The datatype is likely wrong
WARNING: column cpx_diep00 with type DOUBLE contains more than 50% values that could be INTEGERS, the datatype may be incorrect but the test is not considered failed
column cpx_x_coor with type DOUBLE contains less than 50% values that could be INTEGERS, the data type is likely correct
column cpx_y_coor with type DOUBLE contains less than 50% values that could be INTEGERS, the data type is likely correct
datatype decimal is untested
datatype datetime is untested
datatype boolean is untested
column cma with datatype VARCHAR is likely of the correct type
column cma_volgnr with datatype VARCHAR is likely of the correct type
column cpx_jaar with datatype VARCHAR is likely of the correct type
column cpx_code_b with datatype VARCHAR is likely of the correct type
column cpx_code_o with datatype VARCHAR is likely of the correct type
column cpx_code_n with datatype VARCHAR is likely of the correct type
column cpx_begin with datatype VARCHAR is likely of the correct type
column cpx_eind_p with datatype VARCHAR is likely of the correct type
column cpx_zichtb with datatype VARCHAR is likely of the correct type
column cpx_beschr with datatype VARCHAR is likely of the correct type
column cpx_kwets with datatype VARCHAR is likely of the correct type
column cpx_restau with datatype VARCHAR is likely of the correct type
column cpx_consol with datatype VARCHAR is likely of the correct type
column cpx_opmerk with datatype VARCHAR is likely of the correct type
Test A: Er zijn geen kolommen die volledig uit data van een ander type dan het aangegeven type bestaan: False

#### Test B

In [33]:
# komen er waarden van andere typen voor in de kolom
string_contains_only_string = True
for item in dict_datatypes:
    if item == 'string':
        for datatype in dict_datatypes[item]:
            list_of_cols = duckdb.sql(f"""
                                            SELECT column_name FROM (DESCRIBE {table}) WHERE column_type == '{datatype}'
                                            """).fetchall()
            for item in list_of_cols:
            # check voor integers
                string_contains_numeric = duckdb.sql(f"""
                SELECT
                    CASE WHEN EXISTS(
                        SELECT
                            {item[0]}
                        FROM
                            {table}
                        WHERE
                            regexp_full_match({item[0]}, '[0-9]+')
                    )
                    THEN True
                    ELSE False
                    END;
                """).fetchone()[0] # TODO my regex should probably be checked by someone who knows what they're doing...
            # check for float
                string_contains_float = duckdb.sql(fr"""
                SELECT
                    CASE WHEN EXISTS(
                        SELECT
                            {item[0]}
                        FROM
                            {table}
                        WHERE
                            regexp_full_match({item[0]}, '[0-9\.,]+') AND regexp_matches({item[0]}, '[,\.]+')
                    )
                    THEN True
                    ELSE False
                    END;
                """).fetchone()[0] # TODO my regex should probably be checked by someone who knows what they're doing...
            # check for scientific notation numbering
                string_contains_scinum = duckdb.sql(fr"""
                SELECT
                    CASE WHEN EXISTS(
                        SELECT
                            {item[0]}
                        FROM
                            {table}
                        WHERE
                            regexp_full_match({item[0]}, '[0-9E\.,-]+', 'i') AND regexp_matches({item[0]}, 'E', 'i')
                    )
                    THEN True
                    ELSE False
                    END;
                """).fetchone()[0] # TODO my regex should probably be checked by someone who knows what they're doing...
            # check voor boolean
                string_contains_bool = duckdb.sql(f"""
                SELECT
                    CASE WHEN EXISTS(
                        SELECT
                            1
                        FROM
                            {table}
                        WHERE
                            regexp_full_match({item[0]}, '0|1|True|False|Ja|Nee|y|n|j', 'i')
                    )
                    THEN True
                    ELSE False
                    END;
                """).fetchone()[0] # TODO my regex should probably be checked by someone who knows what they're doing...
            # check for date
                regex = r'^\d{4}-\d{2}-\d{2}$|^(0[1-9]|1[0-2])\/(0[1-9]|[12]\d|3[01])\/(19|20)\d{2}$|^(0[1-9]|[12]\d|3[01])\/(0[1-9]|1[0-2])\/(19|20)\d{2}$|^(0[1-9]|[12]\d|3[01])\.(0[1-9]|1[0-2])\.(19|20)\d{2}$' # TODO my regex should probably be checked by someone who knows what they're doing...
                string_contains_date = duckdb.sql(f"""
                SELECT
                    CASE WHEN EXISTS(
                        SELECT
                            1
                        FROM
                            {table}
                        WHERE
                            regexp_full_match({item[0]}, '{regex}', 'i')
                    )
                    THEN True
                    ELSE False
                    END;
                """).fetchone()[0]
                if not string_contains_date and not string_contains_bool and not string_contains_scinum and not string_contains_float and not string_contains_numeric:
                    print(f'kolom {item[0]} met het type {datatype} bevat geen waarden van het verkeerde type')
                else:
                    string_contains_only_string = False

                    concat_string = f"kolom {item[0]} met het type {datatype} heeft mogelijk waarden van het verkeerde type, namelijk:"
                    if string_contains_date:
                        concat_string += ' \ndatum '
                    if string_contains_bool:
                        concat_string += ' \nboolean '
                    if string_contains_scinum:
                        concat_string += ' \ncijfers in wetenschappelijke notering '
                    if string_contains_float:
                        concat_string += ' \nfloat '
                    if string_contains_numeric:
                        concat_string += ' \ncijfer '
                    print( concat_string)

print(f"Test B: Er zijn geen tekstkolommen die data van een ander type bevatten: {string_contains_only_string}. Let op, mogelijk zijn de waarden niet incorrect maar lijken ze op een ander type waarde")

kolom cma met het type VARCHAR heeft mogelijk waarden van het verkeerde type, namelijk:
cijfers in wetenschappelijke notering
cijfer
kolom cma_volgnr met het type VARCHAR heeft mogelijk waarden van het verkeerde type, namelijk:
cijfers in wetenschappelijke notering
kolom cpx_jaar met het type VARCHAR heeft mogelijk waarden van het verkeerde type, namelijk:
float
kolom cpx_code_b met het type VARCHAR bevat geen waarden van het verkeerde type
kolom cpx_code_o met het type VARCHAR bevat geen waarden van het verkeerde type
kolom cpx_code_n met het type VARCHAR bevat geen waarden van het verkeerde type
kolom cpx_begin met het type VARCHAR bevat geen waarden van het verkeerde type
kolom cpx_eind_p met het type VARCHAR bevat geen waarden van het verkeerde type
kolom cpx_zichtb met het type VARCHAR heeft mogelijk waarden van het verkeerde type, namelijk:
boolean
kolom cpx_beschr met het type VARCHAR bevat geen waarden van het verkeerde type
kolom cpx_kwets met het type VARCHAR heeft mogelijk waarden van het verkeerde type, namelijk:
boolean
kolom cpx_restau met het type VARCHAR heeft mogelijk waarden van het verkeerde type, namelijk:
boolean
kolom cpx_consol met het type VARCHAR heeft mogelijk waarden van het verkeerde type, namelijk:
boolean
kolom cpx_opmerk met het type VARCHAR bevat geen waarden van het verkeerde type
Test B: Er zijn geen tekstkolommen die data van een ander type bevatten: False. Let op, mogelijk zijn de waarden niet incorrect maar lijken ze op een ander type waarde

#### Test C

In [34]:
# zijn er kolommen die grootheden en eenheden in dezelfde kolom hebben staan
print("de volgende eenheden worden getest. Er moet voldaan worden aan een patroon [getal] [optionele spatie] [eenheid]")
SI_base_units = ["s", "m", "g", "A", "K" ,"mol", "cd"] # kg vervangen met g voor flexibiliteit
list_prefixes = ["k" ,"h" ,"da" ,"d" ,"c" ,"m" ,"µ"]
list_additional_units = ["%", "°C", "h", "u" ]
units = SI_base_units+list_additional_units

for prefix in list_prefixes:
    for unit in ["m", "g"]:
        units.append(prefix+unit)

print(units) # TODO Thya: mogelijk moet deze op basis van wat we daadwerkelijke tegenkomen nog worden verbeterd. Ik heb in ieder geval niet geprobeerd om compleet te zijn.

de volgende eenheden worden getest. Er moet voldaan worden aan een patroon [getal] [optionele spatie] [eenheid]
['s', 'm', 'g', 'A', 'K', 'mol', 'cd', '%', '°C', 'h', 'u', 'km', 'kg', 'hm', 'hg', 'dam', 'dag', 'dm', 'dg', 'cm', 'cg', 'mm', 'mg', 'µm', 'µg']

In [35]:
str_no_nr_with_unit = True
for item in dict_datatypes:
    if item == 'string':
        for datatype in dict_datatypes[item]:
            list_of_cols = duckdb.sql(f"""
                                            SELECT column_name FROM (DESCRIBE {table}) WHERE column_type == '{datatype}'
                                            """).fetchall()
            for item in list_of_cols:
                # check eerst of er gesplitst kan worden in nummer [optionele spatie] niet nummer
                # check dan of de tekst match met een van de units

                string_contains_nr_with_unit = duckdb.sql(rf"""
                SELECT
                    CASE WHEN EXISTS
                    (
                        SELECT
                            1
                        FROM
                            {table}
                        WHERE
                            (
                                (
                                regexp_matches({item[0]}, '\s([a-zA-Z]*)$')
                                AND
                                regexp_matches({item[0]}, '^([\d,.])')
                                )
                                OR
                                (
                                regexp_matches({item[0]}, '^([\d,.])')
                                AND
                                regexp_matches({item[0]}, '([a-zA-Z])$')
                                )
                            )
                            AND
                                regexp_extract({item[0]}, '([a-zA-Z])$') IN {units}
                    )
                    THEN True
                    ELSE False
                    END;
                """).fetchone()[0]
                if string_contains_nr_with_unit:
                    print(f"{item[0]} met datatype {datatype} bevat mogelijk een combinatie van eenheden en grootheden")
                    str_no_nr_with_unit = False
print(f"Test C: Er zijn geen tekstkolommen die mogelijk bestaan uit een combinatie van grootheden met eenheden: {str_no_nr_with_unit}. Een verdere check is nodig om dit te controleren.")

cma met datatype VARCHAR bevat mogelijk een combinatie van eenheden en grootheden
Test C: Er zijn geen tekstkolommen die mogelijk bestaan uit een combinatie van grootheden met eenheden: False. Een verdere check is nodig om dit te controleren.

In [36]:
# test hier de code
#
# string_contains_bool = duckdb.sql(rf"""
#                         SELECT
#                         test_eenheid_grootheid,
#                         regexp_extract(test_eenheid_grootheid, '([a-zA-Z]*)$')
#                         FROM
#                             test.test
#                         WHERE
#                             (
#                                 (regexp_matches(test_eenheid_grootheid, '\s([a-zA-Z]*)$') AND regexp_matches(test_eenheid_grootheid, '^([\d,.])'))
#                                 OR
#                                 (
#                                 regexp_matches(test_eenheid_grootheid, '^([\d,.])')
#                                 AND
#                                 regexp_matches(test_eenheid_grootheid, '([a-zA-Z])$')
#                                 )
#                             )
#                             AND
#                                 regexp_extract(test_eenheid_grootheid, '([a-zA-Z])$') IN {units};
#                 """).fetchdf()
# string_contains_bool

#### Test D

In [37]:
# duckdb hernoemt kolommen met dezelfde naam door er _1, _2 etc aan toe te voegen.
duplicate_colnames = duckdb.sql(rf"""
SELECT
    CASE WHEN EXISTS(
        SELECT
            1
        FROM
            (DESCRIBE {table})
        WHERE
            regexp_matches(column_name, '_\d$')
            )
    THEN False
    ELSE True
    END;
    """).fetchone()[0]
print(f"Test D: Alle kolommen hebben een andere naam: {duplicate_colnames}")

Test D: Alle kolommen hebben een andere naam: True

#### Test E

In [38]:
duplicate_column_info = False
# TODO deze heb ik even overgeslagen omdat het een hele omslachtige query werd, terwijl het niet zo'n hele belangrijke test is.
print(f"Test E: Er zijn geen kolommen met volledig gedupliceerde informatie: {duplicate_column_info}")

Test E: Er zijn geen kolommen met volledig gedupliceerde informatie: False

#### Test F

In [39]:
list_text_leeg = ['NULL', "None", "-", "/", "Geen", "N/A", "", "niks", "undefined", "empty", "leeg" ] # TODO hier vallen vast nog opties aan toe te voegen.
no_multiple_empty_vals = True
number_of_vals_present = 0
for item in dict_datatypes:
    if item == 'string':
        for datatype in dict_datatypes[item]:
            list_of_cols = duckdb.sql(f"""
                                            SELECT column_name FROM (DESCRIBE {table}) WHERE column_type == '{datatype}'
                                            """).fetchall()
            for item in list_of_cols:
                for empty_val in list_text_leeg:
                    val_present = duckdb.sql(f"""
                    SELECT
                        CASE WHEN EXISTS(
                            SELECT 1
                            FROM {table}
                            WHERE {item[0]} == '{empty_val}')
                        THEN True
                        ELSE False
                        END;
                    """)
                    if val_present:
                        break
                if val_present:
                    number_of_vals_present +=1
                    print(f"Waarde {empty_val} is in gebruik in een tekstveld")
                    break # break uit de for loop zodat er niet meer dan 1x per mogelijkheid wordt opgeteld.
if number_of_vals_present > 1:
    no_multiple_empty_vals = False

print(f"Test F: Er is maximaal 1 waarde voor informatie die niet is ingevuld: {no_multiple_empty_vals}")

Waarde NULL is in gebruik in een tekstveld
Test F: Er is maximaal 1 waarde voor informatie die niet is ingevuld: True

#### Test G

In [40]:
list_text_unknowns = ["?", "onbekend", "unknown", "??", "???", "????", "weet niet"] # TODO hier vallen vast nog opties aan toe te voegen.
list_datetime_unknowns = ["9999-99-99", "1901-01-01", "0000-00-00 00:00:00", "0000-00-00", "9999-99-99 99:99:99"] # TODO hier vallen vast nog opties aan toe te voegen.
# TODO nog geen lijst voor integers en floats. Ik weet dat hier ook bijvoorbeeld 99999 en dergelijken in gebruik zouden kunnen zijn, maar ik kon niet bedenken hoeveel en wanneer dat nou wel of niet de test zou moeten triggeren.
no_multiple_unknown_vals = False
number_of_vals_present_text = 0
number_of_vals_present_datetime = 0
for item in dict_datatypes:
    if item == 'string':
        for datatype in dict_datatypes[item]:
            list_of_cols = duckdb.sql(f"""
                                            SELECT column_name FROM (DESCRIBE {table}) WHERE column_type == '{datatype}'
                                            """).fetchall()
            for item in list_of_cols:
                for unknown_val in list_text_unknowns:
                    val_present = duckdb.sql(f"""
                    SELECT
                        CASE WHEN EXISTS(
                            SELECT 1
                            FROM {table}
                            WHERE {item[0]} == '{unknown_val}')
                        THEN True
                        ELSE False
                        END;
                    """)
                    if val_present:
                        break
                if val_present:
                    number_of_vals_present_text +=1
                    print(f"Waarde {unknown_val} is in gebruik in een tekstveld")
                    break # break uit de for loop zodat er niet meer dan 1x per mogelijkheid wordt opgeteld.
        if number_of_vals_present_text > 1:
            no_multiple_empty_vals = False
            break
    elif item == 'datetime':
        for datatype in dict_datatypes[item]:
            list_of_cols = duckdb.sql(f"""
                                        SELECT column_name FROM (DESCRIBE {table}) WHERE column_type == '{datatype}'
                                        """).fetchall()
            for item in list_of_cols:
                for unknown_val in list_datetime_unknowns:
                    val_present = duckdb.sql(f"""
                        SELECT
                            CASE WHEN EXISTS(
                                SELECT 1
                                FROM {table}
                                WHERE {item[0]} == '{unknown_val}')
                            THEN True
                            ELSE False
                            END;
                        """)
                    if val_present:
                            break
                if val_present:
                    number_of_vals_present_datetime +=1
                    print(f"Waarde {empty_val} is in gebruik in een tekstveld")
                    break # break uit de for loop zodat er niet meer dan 1x per mogelijkheid wordt opgeteld.
if number_of_vals_present_text > 1 or number_of_vals_present_datetime > 1:
    no_multiple_empty_vals = False

print(f"Test F: Er is maximaal 1 waarde voor informatie die niet is ingevuld: {no_multiple_empty_vals}")

Waarde ? is in gebruik in een tekstveld
Test F: Er is maximaal 1 waarde voor informatie die niet is ingevuld: True

## Dimensie 3: Waardenvaliditeit (inhoudelijke correctheid)
* Vraag: Zijn er kolommen waarvan de waarden volgens een bepaalde standaard zijn ingevuld? Zo ja, welke?
* Vraag: Zijn er kolommen die niet volgens een standaard zijn ingevuld, waarbij dat wel zou kunnen? Zo ja, welke?
    * Test A: Kolommen die een standaardwaardenlijst volgen, hebben alleen waarden die in deze standaardwaardenlijst voorkomen.
    * Test B: (tekst) Kolommen die volgens een gestandaardiseerde vorm worden ingevuld, hebben alleen waarden die aan die vorm voldoen
* Vraag: Komt de informatie die in een kolom staat overeen met wat de kolomnaam en/of data dictionary aangeeft?
* Vraag: Is de opbouw van tekst in de tekstuele kolommen consistent?
    * Test C: Er zijn geen kolommen waar geen data in staat.
    * Test D: Er zijn geen rijen die gedupliceerd zijn.
    * Test E: Er zijn geen kolommen waar in elke rij dezelfde data staat.
    * Test F: Er zijn geen (tekst) kolommen met waarden met whitespaces aan het begin of eind

In [41]:
test_resultaten_dim3 = []

In [42]:
# in de lijst staat: [0] welke dataset/schema naam, [1] welke lijst/tabel/ tabel naam, [2], welke eigenschap of kolom / kolom naam [3] uri naar dataset in het geval van linked data, [4] zou kunnen volgen (could), of volgt deze al (should)?
dict_col_with_standard_value = {
    "cpx_code_b": ["Archeologisch_Basis_Register", "complextypen", "Omschrijving", None, "should"],
    "cpx_code_o": ["Archeologisch_Basis_Register", "complextypen", "SIKB Code",None, "should"], # TODO welke is hier nou leidend? SIKB 0102 of ABR?
    "cpx_code_n": ["Archeologisch_Basis_Register", "complextypen", "SIKB Code", None, "should"],
    "cpx_begin" : ["Archeologisch_Basis_Register", "periode", "SIKB Code", None, "should"],
    "cpx_eind_p": ["Archeologisch_Basis_Register", "periode", "SIKB Code", None, "should"]
}
# in de lijst staat: [0] welke standaard (bijvoorbeeld ISO), [1] zou kunnen volgen (could) of volgt deze al (should)?
dict_col_with_standard_form = {
    "cpx_jaar": ["ISO 8601", "could"]
} # TODO: ik ken lang niet alle standaarden. Mogelijk moet dit worden uitgebreid

#### Vraag: Zijn er kolommen waarvan de waarden volgens een bepaalde standaard zijn ingevuld? Zo ja, welke? & Vraag: Zijn er kolommen die niet volgens een standaard zijn ingevuld, waarbij dat wel zou kunnen? Zo ja, welke?

In [43]:
print("gebruik van standaardwaardenlijsten:\n")
for item in dict_col_with_standard_value:
    if dict_col_with_standard_value[item][4] == "could":
        print(f"{item} zou gebruik kunnen maken van {dict_col_with_standard_value[item][0]} : {dict_col_with_standard_value[item][1]}")
    elif dict_col_with_standard_value[item][4] == "should":
        print(f"{item} maakt gebruik van {dict_col_with_standard_value[item][0]} : {dict_col_with_standard_value[item][1]}")
print("\ngebruik van gestandaardiseerde vormen: \n")
for item in dict_col_with_standard_form:
    if dict_col_with_standard_form[item][1] == "could":
        print(f"{item} zou gebruik kunnen maken van {dict_col_with_standard_form[item][0]}")
    elif dict_col_with_standard_form[item][1] == "should":
        print(f"{item} maakt gebruik van {dict_col_with_standard_form[item][0]}")

gebruik van standaardwaardenlijsten:

cpx_code_b maakt gebruik van Archeologisch_Basis_Register : complextypen
cpx_code_o maakt gebruik van Archeologisch_Basis_Register : complextypen
cpx_code_n maakt gebruik van Archeologisch_Basis_Register : complextypen
cpx_begin maakt gebruik van Archeologisch_Basis_Register : periode
cpx_eind_p maakt gebruik van Archeologisch_Basis_Register : periode

gebruik van gestandaardiseerde vormen:

cpx_jaar zou gebruik kunnen maken van ISO 8601

#### Test A

In [44]:
# TODO Note T: hier heb ik nu gebruik gemaakt van de domeintabellen van de SIKB, maar dit zou gebruik moeten maken van de linked data van het ABR. Het was voor mij even te hoog gegrepen om ook SPARQL te leren om deze lijsten in te laden, dus dit zal iemand anders even moeten aanvullen.
# ABR versie

# activeer triple/sparql toegang in duckdb
# duckdb.sql(f"""INSTALL rdf FROM community;
#                 LOAD rdf;""") # NOTE: let op dit is een community extension

# maak een lijst van complextypen uit het ABR

# maak een lijst van perioden uit het ABR

# maak een lijst met ABRcodes voor complextypen uit het ABR

In [45]:
# SIKB versie # TODO vervangen met ABR linked data inladen.
# SIKB domeinlijst complextypen TODO zeer ad hoc! Geen voorbeeld van hoe het inladen van standaardwaardenlijsten in de eindversie/het DAP gedaan moet worden!
for item in dict_col_with_standard_value:
    if dict_col_with_standard_value[item][0] == "Archeologisch_Basis_Register":
        duckdb.sql(f"""CREATE SCHEMA IF NOT EXISTS {dict_col_with_standard_value[item][0]}""")
        if dict_col_with_standard_value[item][1] == "complextypen":
            duckdb.sql(f"""CREATE TABLE IF NOT EXISTS {dict_col_with_standard_value[item][0]}.{dict_col_with_standard_value[item][1]} AS SELECT * FROM read_csv('./data/SIKB_domeintabel_5_Complextype.csv') """) # file is lokaal geinstalleerd
        elif dict_col_with_standard_value[item][1] == "periode":
            duckdb.sql(f"""CREATE TABLE IF NOT EXISTS {dict_col_with_standard_value[item][0]}.{dict_col_with_standard_value[item][1]} AS SELECT * FROM read_csv('./data/SIKB_domeintabel_5_Periode.csv') """) # file is lokaal geinstalleerd

In [46]:
standard_lists_followed = True
for item in dict_col_with_standard_value:
    if dict_col_with_standard_value[item][4] == "should": #

        try:
            val = duckdb.sql(f"""
            SELECT
                LIST_HAS_ALL(
                    (
                    SELECT
                        LIST(DISTINCT({item}))
                    FROM {table}
                    )
                    ,
                    (
                    SELECT
                        LIST("{dict_col_with_standard_value[item][2]}")
                    FROM
                        {dict_col_with_standard_value[item][0]}.{dict_col_with_standard_value[item][1]}
                    WHERE

                        "Eind geldigheid" IS NULL
                    )
                );
            """).fetchone()[0]
        except Exception as e: # zou bij voorkeur alleen de "BinderException" pakken, maar duckdb exceptions zijn strings, geen echte exceptions.
            val = duckdb.sql(f"""
            SELECT
                LIST_HAS_ALL(
                    (
                    SELECT
                        LIST(DISTINCT({item}))
                    FROM {table}
                    )
                    ,
                    (
                    SELECT
                        LIST("{dict_col_with_standard_value[item][2]}")
                    FROM
                        {dict_col_with_standard_value[item][0]}.{dict_col_with_standard_value[item][1]}
                    )
                );
            """).fetchone()[0]

        print(f"{item} volgt de beoogde standaardwaardenlijst: {val}")
        if not val:
            standard_lists_followed = False
print(f"Test A: Kolommen die een standaardwaardenlijst volgen, hebben alleen waarden die in deze standaardwaardenlijst voorkomen.: {standard_lists_followed}.\n"
      f"let op: alleen kolommen die al een standaardwaardenlijst volgen zijn getest. Kolommen die een standaardwaardenlijst ZOUDEN kunnen volgen worden niet getest.")
test_resultaten_dim3.append(standard_lists_followed)

cpx_code_b volgt de beoogde standaardwaardenlijst: False
cpx_code_o volgt de beoogde standaardwaardenlijst: False
cpx_code_n volgt de beoogde standaardwaardenlijst: False
cpx_begin volgt de beoogde standaardwaardenlijst: False
cpx_eind_p volgt de beoogde standaardwaardenlijst: False
Test A: Kolommen die een standaardwaardenlijst volgen, hebben alleen waarden die in deze standaardwaardenlijst voorkomen.: False.
let op: alleen kolommen die al een standaardwaardenlijst volgen zijn getest. Kolommen die een standaardwaardenlijst ZOUDEN kunnen volgen worden niet getest.

In [47]:
duckdb.sql(f"""DESCRIBE Archeologisch_Basis_Register.periode""")

┌───────────────────┬─────────────┬─────────┬─────────┬─────────┬─────────┐
│    column_name    │ column_type │  null   │   key   │ default │  extra  │
│      varchar      │   varchar   │ varchar │ varchar │ varchar │ varchar │
├───────────────────┼─────────────┼─────────┼─────────┼─────────┼─────────┤
│ ID                │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ SIKB Code         │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ Omschrijving      │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ Begin geldigheid  │ DATE        │ YES     │ NULL    │ NULL    │ NULL    │
│ Laatste wijziging │ DATE        │ YES     │ NULL    │ NULL    │ NULL    │
│ BRO SAD IMBRO\A   │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ BRO SAD IMBRO     │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ BRO SLD IMBRO\A   │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ BRO SLD IMBRO     │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
└───────────────────┴─────────────┴─────────┴─────────┴─────────┴─────────┘

#### Test B

In [48]:
standard_forms_followed = True
for item in dict_col_with_standard_form:
    if dict_col_with_standard_form[item][1] == "should":
        if dict_col_with_standard_form[item][0]== "ISO 8601":
            # TODO nog veel meer standaarden toepassen
            regex = r'^\d{4}-\d{2}-\d{2}$|^(0[1-9]|1[0-2])\/(0[1-9]|[12]\d|3[01])\/(19|20)\d{2}$|^(0[1-9]|[12]\d|3[01])\/(0[1-9]|1[0-2])\/(19|20)\d{2}$|^(0[1-9]|[12]\d|3[01])\.(0[1-9]|1[0-2])\.(19|20)\d{2}$' # TODO my regex should probably be checked by someone who knows what they're doing...
            string_follows_standard = duckdb.sql(f"""
                SELECT
                    (
                    SELECT
                        COUNT()
                    FROM
                        {table}
                    WHERE
                        regexp_full_match({item}, '{regex}', 'i')
                    )
                    ==
                    (SELECT
                        COUNT()
                    FROM
                        {table}
                    );
                """).fetchone()[0]
            print(f"kolom {item} volgt ISO 8601: {string_follows_standard}")
            if not string_follows_standard:
                standard_forms_followed = False
            # duckdb volgt in hun date time datatypen al automatisch ISO 8601, dus dit hoeft niet getest te worden. Alleen als de datums nog in een tekstkolom staan.
print(f"Test B: (tekst) Kolommen die volgens een gestandaardiseerde vorm worden ingevuld, hebben alleen waarden die aan die vorm voldoen: {standard_forms_followed}.\n"
      f"let op: alleen kolommen die al een standaardvorm volgen zijn getest. Kolommen die een standaardvorm ZOUDEN kunnen volgen worden niet getest.")
test_resultaten_dim3.append(standard_forms_followed)

Test B: (tekst) Kolommen die volgens een gestandaardiseerde vorm worden ingevuld, hebben alleen waarden die aan die vorm voldoen: True.
let op: alleen kolommen die al een standaardvorm volgen zijn getest. Kolommen die een standaardvorm ZOUDEN kunnen volgen worden niet getest.

#### Vraag: Komt de informatie die in een kolom staat overeen met wat de kolomnaam en/of data dictionary aangeeft?
Ja, al is van cpx_monito en cpx_jaar niet te achterhalen welke informatie hier precies zou moeten staan.

In [49]:
# hier kan verder qua code niks mee te worden gedaan, dit is puur interpretatie.
duckdb.sql(f"""SELECT * FROM {table} LIMIT 10 """).fetchdf()

,complex_id,terreinnum,rijksmonum,cma,cma_volgnr,cpx_monito,cpx_jaar,cpx_code_b,cpx_code_o,cpx_code_n,cpx_begin,cpx_eind_p,cpx_zichtb,cpx_beschr,cpx_kwets,cpx_restau,cpx_consol,cpx_diepte,cpx_diep00,cpx_x_coor,cpx_y_coor,cpx_opmerk,geometry
0,52.0,60.0,330191.0,67A-002,None,3324,None,Klooster,RKLO,CTHD.KLO,Middeleeuwen laat,Middeleeuwen laat,onbekend,Resten van een klooster,onbekend,None,None,0.0,0.0,19494.10005,366239.100025,None,"[1, 235, 3, 0, 0, 1, 0, 0, 0, 13, 0, 0, 0, 150..."
1,54.0,61.0,330202.0,67A3,None,3327,None,begraving,GX,BGV,Romeinse tijd midden,Romeinse tijd laat,onbekend,Sporen van begraving,onbekend,None,None,0.0,0.0,19789.50010,366276.499975,None,"[1, 238, 3, 0, 0, 2, 0, 0, 0, 1, 235, 3, 0, 0,..."
2,53.0,61.0,330202.0,67A3,None,3326,None,Bewoning (inclusief verdediging),NX,BEWV,Romeinse tijd midden,Romeinse tijd laat,onbekend,Sporen van bewoning,onbekend,None,None,0.0,0.0,19789.50010,366276.499975,None,"[1, 238, 3, 0, 0, 2, 0, 0, 0, 1, 235, 3, 0, 0,..."
3,56.0,62.0,330373.0,67A-004,None,3332,None,Weg,IWEG,INFR.WEG,Romeinse tijd,Romeinse tijd,onbekend,Resten van een weg,onbekend,None,None,0.0,0.0,19883.89990,366405.600100,None,"[1, 235, 3, 0, 0, 1, 0, 0, 0, 7, 0, 0, 0, 94, ..."
4,57.0,62.0,330373.0,67A-004,None,3331,None,Bewoning (inclusief verdediging),NX,BEWV,Middeleeuwen laat,Middeleeuwen laat,onbekend,Sporen van bewoning,onbekend,None,None,0.0,0.0,19883.89990,366405.600100,None,"[1, 235, 3, 0, 0, 1, 0, 0, 0, 7, 0, 0, 0, 94, ..."
5,55.0,62.0,330373.0,67A-004,None,3330,None,Bewoning (inclusief verdediging),NX,BEWV,Romeinse tijd,Romeinse tijd,onbekend,Sporen van bewoning,onbekend,None,None,0.0,0.0,19883.89990,366405.600100,None,"[1, 235, 3, 0, 0, 1, 0, 0, 0, 7, 0, 0, 0, 94, ..."
6,59.0,63.0,330379.0,67A-005,None,3335,None,Legerplaats,VLP,BEWV.VLP,Romeinse tijd,Romeinse tijd,onbekend,Resten van een legerplaats,onbekend,None,None,0.0,0.0,19691.99995,366465.900025,None,"[1, 235, 3, 0, 0, 1, 0, 0, 0, 42, 0, 0, 0, 127..."
7,60.0,63.0,330379.0,67A-005,None,3341,None,Weg,IWEG,INFR.WEG,Romeinse tijd,Romeinse tijd,onbekend,Resten van een weg,onbekend,None,None,0.0,0.0,19691.99995,366465.900025,None,"[1, 235, 3, 0, 0, 1, 0, 0, 0, 42, 0, 0, 0, 127..."
8,61.0,63.0,330379.0,67A-005,None,3340,None,Wal/omwalling,VWAL,Wal,Nieuwe tijd,Nieuwe tijd,onbekend,Resten van een wal,onbekend,None,None,0.0,0.0,19691.99995,366465.900025,None,"[1, 235, 3, 0, 0, 1, 0, 0, 0, 42, 0, 0, 0, 127..."
9,58.0,63.0,330379.0,67A-005,None,3333,None,Bewoning (inclusief verdediging),NX,BEWV,Romeinse tijd,Romeinse tijd,onbekend,Sporen van bewoning,onbekend,None,None,0.0,0.0,19691.99995,366465.900025,None,"[1, 235, 3, 0, 0, 1, 0, 0, 0, 42, 0, 0, 0, 127..."

#### Vraag: Is de opbouw van tekst in de tekstuele kolommen consistent?

In [50]:
# geen testbare vraag zonder eerst handmatig de patronen te identificeren, dus niet te automatiseren. Voor nu overgeslagen.

#### Test C

In [51]:
no_null_columns = True
list_of_cols = duckdb.sql(f"""
                          SELECT column_name FROM (DESCRIBE {table})
                          """).fetchall()
for col in list_of_cols:
    val = duckdb.sql(f"""
    SELECT
        (
        SELECT
            COUNT()
        FROM
            {table}
        WHERE
            {col[0]} IS NULL
        )
        !=
        (
        SELECT
            COUNT()
        FROM
            {table}
        );""").fetchone()[0]
    if not val:
        no_null_columns = False
        print(f"kolom {col[0]} bestaat uit alleen maar NULL waarden")

print(f" Test C: Er zijn geen kolommen waar geen data in staat: {no_null_columns}")
test_resultaten_dim3.append(no_null_columns)

 Test C: Er zijn geen kolommen waar geen data in staat: True

#### Test D

In [52]:
list_of_cols = duckdb.sql(f"""
                          SELECT column_name FROM (DESCRIBE {table})
                          """).fetchdf()["column_name"].to_list()

no_duplicate_rows = duckdb.sql(f"""
SELECT
    (SELECT COUNT(DISTINCT({', '.join(list_of_cols)})) FROM {table})
    ==
    (SELECT COUNT() FROM {table});
    """).fetchone()[0]


print(f"Test D: Er zijn geen rijen die volledig gedupliceerd zijn: {no_duplicate_rows}")
test_resultaten_dim3.append(no_duplicate_rows)

Test D: Er zijn geen rijen die volledig gedupliceerd zijn: True

#### Test E

In [53]:
no_single_val_cols = True
list_of_cols = duckdb.sql(f"""
                          SELECT column_name FROM (DESCRIBE {table})
                          """).fetchall()
for col in list_of_cols:
    val = duckdb.sql(f"""
    SELECT
     (SELECT COUNT(DISTINCT({col[0]})) FROM {table})
     >1""")
    if not val:
        no_single_val_cols = False


print(f"Test E: Er zijn geen kolommen waar in elke rij dezelfde data staat: {no_single_val_cols}")
test_resultaten_dim3.append(no_single_val_cols)

Test E: Er zijn geen kolommen waar in elke rij dezelfde data staat: True

#### Test F

In [54]:
no_trailing_or_leading_whitespaces = True
for item in dict_datatypes:
    if item == 'string':
        for datatype in dict_datatypes[item]:
            list_of_cols = duckdb.sql(f"""
                                            SELECT column_name FROM (DESCRIBE {table}) WHERE column_type == '{datatype}'
                                            """).fetchall()
            for item in list_of_cols:
                val = duckdb.sql(f"""
                SELECT
                    CASE WHEN EXISTS(
                        SELECT
                            1
                        FROM
                            {table}
                        WHERE
                            ends_with({item[0]}, ' ')
                            OR
                            starts_with({item[0]}, ' ')
                        )
                    THEN False
                    ELSE True
                    END;
                    """).fetchone()[0]
                if not val:
                    no_trailing_or_leading_whitespaces = False


print(f"Test F: Er zijn geen (tekst) kolommen met waarden met whitespaces aan het begin of eind: {no_trailing_or_leading_whitespaces}")
test_resultaten_dim3.append(no_trailing_or_leading_whitespaces)

Test F: Er zijn geen (tekst) kolommen met waarden met whitespaces aan het begin of eind: True

#### Resultaten dimensie 3

In [55]:
aantal_testen_succes_dim3 = 0

for test in test_resultaten_dim3:
    if test:
        aantal_testen_succes_dim3 += 1

if len(test_resultaten_dim3) == aantal_testen_succes_dim3:
    print(f"Er zijn {len(test_resultaten_dim3)} tests uitgevoerd voor dimensie 3. Daarvan is/zijn aan {aantal_testen_succes_dim3} test(en) voldaan. Dat betekent dat aan datakwaliteitsdimensie 3 in zijn geheel is voldaan")
    dk_dimensies_voldaan +=1
else:
    print(f"Er zijn {len(test_resultaten_dim3)} tests uitgevoerd voor dimensie 3. Daarvan is/zijn aan {aantal_testen_succes_dim3} test(en) voldaan. Dat betekent dat aan datakwaliteitsdimensie 3 NIET in zijn geheel is voldaan.")

Er zijn 6 tests uitgevoerd voor dimensie 3. Daarvan is/zijn aan 5 test(en) voldaan. Dat betekent dat aan datakwaliteitsdimensie 3 NIET in zijn geheel is voldaan.

## Dimensie 4: Granulariteit en eenduidige representatie
* Vraag: Is het niveau van detail van de data _binnen_ kolommen hetzelfde?
    * Test A: Is de eenheid van de kolom consistent? (Notitie Thya: Dit kan alleen getest worden als de eenheid ook in die kolom of een andere kolom is vastgelegd).
* Vraag: Zijn er geaggregeerde kolommen?
    * Test B: Er zijn geen kolommen die bestaan uit een samentrekking van twee andere kolommen die ook in de dataset staan.
    * Test C: Er zijn geen verborgen aggregaties, bestaande uit een waarde, een scheidingsteken, gevolgd door nog een waarde
* Vraag: Zijn er kolommen waarin andere kolommen met elkaar verrekend zijn?
    * Test [x] notitie Thya: Er kunnen hier testen uitgevoerd worden, maar er zijn zo veel verschillende manieren van verrekenen, dat dit nooit volledig gecheckt zou kunnen worden. Bovendien is het niet altijd slecht, dus dit kan waarschijnlijk beter in goeie samenspraak met de domeindeskundige)
* Vraag: Zijn er kolommen waarbij het niveau van detail niet voldoet voor het beoogde doel?
* Vraag: Staan de waarden en de indicatie van precisie van deze waarde in losse kolommen? Zo ja, is het duidelijk welke precisiekolom bij welke kolom hoort (ook wanneer kolommen gehusseld worden)?
* Vraag: Is van kolommen waar topografische benamingen in staat duidelijk over welk type geografische eenheid dit gaat?
    * Test D: Staat in een kolom met provincies alleen provincies? (inclusief historische)
    * Test E: Staat in een kolom met gemeenten alleen gemeenten? (inclusief historische)
    * Test F: Staat in een kolom met plaatsen alleen plaatsen? (inclusief historische)
    * Test G: Staat in een kolom met landen alleen landen? (inclusief historische en niet-erkende)

#### Vraag: Is het niveau van detail van de data _binnen_ kolommen hetzelfde?
**Dit antwoord vereist (domein)kennis van de dataset.**

- voor de complex code en periode kolommen geldt dat sommige waarden subcategorieën zijn van andere waarden. Dit is in deze kolommen echter wenselijk, omdat deze gebruik (gaan) maken van een gestructureerde linked data standaardwaardenlijst.
- Verder zijn er geen problemen.

In [56]:
duckdb.sql(f"""SELECT * FROM {table}""").fetchdf()

,complex_id,terreinnum,rijksmonum,cma,cma_volgnr,cpx_monito,cpx_jaar,cpx_code_b,cpx_code_o,cpx_code_n,cpx_begin,cpx_eind_p,cpx_zichtb,cpx_beschr,cpx_kwets,cpx_restau,cpx_consol,cpx_diepte,cpx_diep00,cpx_x_coor,cpx_y_coor,cpx_opmerk,geometry
0,52.0,60.0,330191.0,67A-002,NaN,3324,NaN,Klooster,RKLO,CTHD.KLO,Middeleeuwen laat,Middeleeuwen laat,onbekend,Resten van een klooster,onbekend,NaN,NaN,0.0,0.0,19494.10005,366239.100025,NaN,"[1, 235, 3, 0, 0, 1, 0, 0, 0, 13, 0, 0, 0, 150..."
1,54.0,61.0,330202.0,67A3,NaN,3327,NaN,begraving,GX,BGV,Romeinse tijd midden,Romeinse tijd laat,onbekend,Sporen van begraving,onbekend,NaN,NaN,0.0,0.0,19789.50010,366276.499975,NaN,"[1, 238, 3, 0, 0, 2, 0, 0, 0, 1, 235, 3, 0, 0,..."
2,53.0,61.0,330202.0,67A3,NaN,3326,NaN,Bewoning (inclusief verdediging),NX,BEWV,Romeinse tijd midden,Romeinse tijd laat,onbekend,Sporen van bewoning,onbekend,NaN,NaN,0.0,0.0,19789.50010,366276.499975,NaN,"[1, 238, 3, 0, 0, 2, 0, 0, 0, 1, 235, 3, 0, 0,..."
3,56.0,62.0,330373.0,67A-004,NaN,3332,NaN,Weg,IWEG,INFR.WEG,Romeinse tijd,Romeinse tijd,onbekend,Resten van een weg,onbekend,NaN,NaN,0.0,0.0,19883.89990,366405.600100,NaN,"[1, 235, 3, 0, 0, 1, 0, 0, 0, 7, 0, 0, 0, 94, ..."
4,57.0,62.0,330373.0,67A-004,NaN,3331,NaN,Bewoning (inclusief verdediging),NX,BEWV,Middeleeuwen laat,Middeleeuwen laat,onbekend,Sporen van bewoning,onbekend,NaN,NaN,0.0,0.0,19883.89990,366405.600100,NaN,"[1, 235, 3, 0, 0, 1, 0, 0, 0, 7, 0, 0, 0, 94, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4121,2479.0,1697.0,532464.0,NaN,NaN,0,NaN,"Nederzetting, onbepaald",NaN,NaN,Neolithicum laat: 2850 - 2000 vC,Neolithicum laat: 2850 - 2000 vC,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.00000,0.000000,NaN,"[1, 235, 3, 0, 0, 1, 0, 0, 0, 6, 0, 0, 0, 186,..."
4122,2478.0,1697.0,532464.0,NaN,NaN,0,NaN,"Graf, onbepaald",NaN,NaN,Neolithicum midden: 4200 - 2850 vC,Neolithicum midden: 4200 - 2850 vC,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.00000,0.000000,NaN,"[1, 235, 3, 0, 0, 1, 0, 0, 0, 6, 0, 0, 0, 186,..."
4123,50998.0,20016.0,532452.0,NaN,NaN,0,NaN,aardwerk,NaN,NaN,Middeleeuwen volle,Middeleeuwen volle,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.00000,0.000000,NaN,"[1, 235, 3, 0, 0, 1, 0, 0, 0, 35, 0, 0, 0, 102..."
4124,50999.0,20016.0,532452.0,NaN,NaN,0,NaN,Moated site,NaN,NaN,Middeleeuwen laat A,Middeleeuwen laat A,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.00000,0.000000,NaN,"[1, 235, 3, 0, 0, 1, 0, 0, 0, 35, 0, 0, 0, 102..."
4125,50997.0,20016.0,532452.0,NaN,NaN,0,NaN,"Nederzetting, onbepaald",NaN,NaN,ijzertijd,Middeleeuwen laat,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.00000,0.000000,NaN,"[1, 235, 3, 0, 0, 1, 0, 0, 0, 35, 0, 0, 0, 102..."

#### Vraag: Zijn er geaggregeerde kolommen (samentrekkingen van 2 kolommen die beiden in de dataset staan)
**Dit antwoord vereist (domein)kennis van de dataset.**

 - De kolom "cma" bevat technische gezien en samentrekking, omdat het eerste deel van de code (00X) refereert naar een kaartblad op een topografische kaart, en het tweede deel van de code (-xxx) naar het vlak op het kaartblad. Er is echter besloten dat dit samengetrokken nummer het cma nummer is, en dit komt dan overeen met het archief en hoe deze gestructureerd is, dus dit is niet onwenselijk. (vanwege vervuiling in deze kolom wordt deze in Test A niet geidentificeerd).
 - De complex code en periode kolommen bevatten samentrekkingen vanwege de bij de vorige vraag genoemde subcategorieën. Deze zijn niet ongewenst.

#### Test A

In [57]:
# verzamel eerst (handmatig) de kolommen met eenheden
# key =  kolomnaam, val = kolom is geaggregeerd met de grootheden true/false
dict_col_w_units = None

# dict_col_w_units = {
#     kolomnaam: False

In [58]:
no_mixed_units = True
if not dict_col_w_units:
    print("Er zijn geen kolommen met eenheden, test automatisch gehaald")
else:
    # TODO deze zijn er in het complexenbestand niet, dus dit heb ik voor nu overgeslagen
    pass

Er zijn geen kolommen met eenheden, test automatisch gehaald

#### Test B

In [59]:
# maak een dict met combinaties voor alle kolommen

list_of_cols =duckdb.sql(f"""SELECT column_name FROM (DESCRIBE {table})""").fetchdf()["column_name"].to_list()

dict_of_col_combinations = {}
for column in list_of_cols:
    dict_of_col_combinations[column] = []

    for column2 in list_of_cols:
        if column != column2 and column2 not in dict_of_col_combinations: # vermijd checken met zichzelf en tweemaal checken.
            dict_of_col_combinations[column].append(column2)

for key in dict_of_col_combinations:
    print(key, dict_of_col_combinations[key])

complex_id ['terreinnum', 'rijksmonum', 'cma', 'cma_volgnr', 'cpx_monito', 'cpx_jaar', 'cpx_code_b', 'cpx_code_o', 'cpx_code_n', 'cpx_begin', 'cpx_eind_p', 'cpx_zichtb', 'cpx_beschr', 'cpx_kwets', 'cpx_restau', 'cpx_consol', 'cpx_diepte', 'cpx_diep00', 'cpx_x_coor', 'cpx_y_coor', 'cpx_opmerk', 'geometry']
terreinnum ['rijksmonum', 'cma', 'cma_volgnr', 'cpx_monito', 'cpx_jaar', 'cpx_code_b', 'cpx_code_o', 'cpx_code_n', 'cpx_begin', 'cpx_eind_p', 'cpx_zichtb', 'cpx_beschr', 'cpx_kwets', 'cpx_restau', 'cpx_consol', 'cpx_diepte', 'cpx_diep00', 'cpx_x_coor', 'cpx_y_coor', 'cpx_opmerk', 'geometry']
rijksmonum ['cma', 'cma_volgnr', 'cpx_monito', 'cpx_jaar', 'cpx_code_b', 'cpx_code_o', 'cpx_code_n', 'cpx_begin', 'cpx_eind_p', 'cpx_zichtb', 'cpx_beschr', 'cpx_kwets', 'cpx_restau', 'cpx_consol', 'cpx_diepte', 'cpx_diep00', 'cpx_x_coor', 'cpx_y_coor', 'cpx_opmerk', 'geometry']
cma ['cma_volgnr', 'cpx_monito', 'cpx_jaar', 'cpx_code_b', 'cpx_code_o', 'cpx_code_n', 'cpx_begin', 'cpx_eind_p', 'cpx_zichtb', 'cpx_beschr', 'cpx_kwets', 'cpx_restau', 'cpx_consol', 'cpx_diepte', 'cpx_diep00', 'cpx_x_coor', 'cpx_y_coor', 'cpx_opmerk', 'geometry']
cma_volgnr ['cpx_monito', 'cpx_jaar', 'cpx_code_b', 'cpx_code_o', 'cpx_code_n', 'cpx_begin', 'cpx_eind_p', 'cpx_zichtb', 'cpx_beschr', 'cpx_kwets', 'cpx_restau', 'cpx_consol', 'cpx_diepte', 'cpx_diep00', 'cpx_x_coor', 'cpx_y_coor', 'cpx_opmerk', 'geometry']
cpx_monito ['cpx_jaar', 'cpx_code_b', 'cpx_code_o', 'cpx_code_n', 'cpx_begin', 'cpx_eind_p', 'cpx_zichtb', 'cpx_beschr', 'cpx_kwets', 'cpx_restau', 'cpx_consol', 'cpx_diepte', 'cpx_diep00', 'cpx_x_coor', 'cpx_y_coor', 'cpx_opmerk', 'geometry']
cpx_jaar ['cpx_code_b', 'cpx_code_o', 'cpx_code_n', 'cpx_begin', 'cpx_eind_p', 'cpx_zichtb', 'cpx_beschr', 'cpx_kwets', 'cpx_restau', 'cpx_consol', 'cpx_diepte', 'cpx_diep00', 'cpx_x_coor', 'cpx_y_coor', 'cpx_opmerk', 'geometry']
cpx_code_b ['cpx_code_o', 'cpx_code_n', 'cpx_begin', 'cpx_eind_p', 'cpx_zichtb', 'cpx_beschr', 'cpx_kwets', 'cpx_restau', 'cpx_consol', 'cpx_diepte', 'cpx_diep00', 'cpx_x_coor', 'cpx_y_coor', 'cpx_opmerk', 'geometry']
cpx_code_o ['cpx_code_n', 'cpx_begin', 'cpx_eind_p', 'cpx_zichtb', 'cpx_beschr', 'cpx_kwets', 'cpx_restau', 'cpx_consol', 'cpx_diepte', 'cpx_diep00', 'cpx_x_coor', 'cpx_y_coor', 'cpx_opmerk', 'geometry']
cpx_code_n ['cpx_begin', 'cpx_eind_p', 'cpx_zichtb', 'cpx_beschr', 'cpx_kwets', 'cpx_restau', 'cpx_consol', 'cpx_diepte', 'cpx_diep00', 'cpx_x_coor', 'cpx_y_coor', 'cpx_opmerk', 'geometry']
cpx_begin ['cpx_eind_p', 'cpx_zichtb', 'cpx_beschr', 'cpx_kwets', 'cpx_restau', 'cpx_consol', 'cpx_diepte', 'cpx_diep00', 'cpx_x_coor', 'cpx_y_coor', 'cpx_opmerk', 'geometry']
cpx_eind_p ['cpx_zichtb', 'cpx_beschr', 'cpx_kwets', 'cpx_restau', 'cpx_consol', 'cpx_diepte', 'cpx_diep00', 'cpx_x_coor', 'cpx_y_coor', 'cpx_opmerk', 'geometry']
cpx_zichtb ['cpx_beschr', 'cpx_kwets', 'cpx_restau', 'cpx_consol', 'cpx_diepte', 'cpx_diep00', 'cpx_x_coor', 'cpx_y_coor', 'cpx_opmerk', 'geometry']
cpx_beschr ['cpx_kwets', 'cpx_restau', 'cpx_consol', 'cpx_diepte', 'cpx_diep00', 'cpx_x_coor', 'cpx_y_coor', 'cpx_opmerk', 'geometry']
cpx_kwets ['cpx_restau', 'cpx_consol', 'cpx_diepte', 'cpx_diep00', 'cpx_x_coor', 'cpx_y_coor', 'cpx_opmerk', 'geometry']
cpx_restau ['cpx_consol', 'cpx_diepte', 'cpx_diep00', 'cpx_x_coor', 'cpx_y_coor', 'cpx_opmerk', 'geometry']
cpx_consol ['cpx_diepte', 'cpx_diep00', 'cpx_x_coor', 'cpx_y_coor', 'cpx_opmerk', 'geometry']
cpx_diepte ['cpx_diep00', 'cpx_x_coor', 'cpx_y_coor', 'cpx_opmerk', 'geometry']
cpx_diep00 ['cpx_x_coor', 'cpx_y_coor', 'cpx_opmerk', 'geometry']
cpx_x_coor ['cpx_y_coor', 'cpx_opmerk', 'geometry']
cpx_y_coor ['cpx_opmerk', 'geometry']
cpx_opmerk ['geometry']
geometry []

In [60]:
no_aggregate_cols = True
# test of er inderdaad geen gecombineerde kolommen zijn.
# TODO Alleen directe aggregaties worden gecheckt, aggregaties met separators worden niet gecheckt! Mogelijk is dit wel wenselijk, maar er zijn zo veel opties voor separators...
# TODO dit duurt vrij lang (35 seconden), mogelijk zal dit voor grotere datasets nog veel langer duren, omdat het een exponentieel lagere lijst wordt naarmate er meer kolommen zijn. Is er een snellere manier?

for item in dict_datatypes:
    if item == 'string':
        for datatype in dict_datatypes[item]:
            list_of_cols = duckdb.sql(f"""
                                    SELECT column_name FROM (DESCRIBE {table}) WHERE column_type == '{datatype}'
                                    """).fetchdf()["column_name"].to_list()
            for column in list_of_cols:
                print(f"checking {column}...")
                for column2 in dict_of_col_combinations:
                    for column3 in dict_of_col_combinations[column2]:
                        val = duckdb.sql(f"""
                        SELECT
                            (SELECT COUNT()
                            FROM {table}
                            WHERE
                                {column}
                                ==
                                ({column2} || {column3})
                            )
                            ==
                            (SELECT COUNT()
                            FROM {table}
                            )
                                    ;
                        """).fetchone()[0]
                        if val:
                            no_aggregate_cols = False
                            print(f"{column} is een aggregatie van {column2} en {column3}")

print(f"Er zijn geen kolommen die bestaan uit een samentrekking van twee andere kolommen: {no_aggregate_cols}. \n Let op! Alleen directe aggregaties worden getest, er is geen rekening gehouden met aggregatiekolommen waarbij een scheidingsteken is gebruikt!")

checking cma...
checking cma_volgnr...
checking cpx_jaar...
checking cpx_code_b...
checking cpx_code_o...
checking cpx_code_n...
checking cpx_begin...
checking cpx_eind_p...
checking cpx_zichtb...
checking cpx_beschr...
checking cpx_kwets...
checking cpx_restau...
checking cpx_consol...
checking cpx_opmerk...
Er zijn geen kolommen die bestaan uit een samentrekking van twee andere kolommen: True.
 Let op! Alleen directe aggregaties worden getest, er is geen rekening gehouden met aggregatiekolommen waarbij een scheidingsteken is gebruikt!

#### Vraag: Zijn er kolommen waarin andere kolommen met elkaar verrekend zijn?
**Voor deze vraag is (domein)kennis van de dataset vereist**

- Nee

#### Test C

In [61]:
no_hidden_aggregates = True
list_of_common_separators = [r"\.", ",", ", ", ";", "-", " - ", "_", r"\/", r"\/ ", r" \/ ", r"\t", r"\|", ":"] # is al inclusief escape characters waar nodig.
print(f"de volgende scheidingstekens wordt voor gecontroleerd: {list_of_common_separators}. (Let op, inclusief escape characters (\\) waar dit nodig is voor de code)\n")

# regex voor de separators wordt flexibel gegenereerd zodat we flexibel meer toe kunnen voegen.
regex_separator = "(?:"
for separator in list_of_common_separators:
    if list_of_common_separators.index(separator) == len(list_of_common_separators)-1:
        regex_separator = regex_separator + separator
    else:
        regex_separator = regex_separator+separator+"|"
regex_separator = regex_separator + ")"

for item in dict_datatypes:
    if item == 'string':
        for datatype in dict_datatypes[item]:
            list_of_cols = duckdb.sql(f"""
                            SELECT column_name FROM (DESCRIBE {table}) WHERE column_type == '{datatype}'
                            """).fetchdf()["column_name"].to_list()
            for column in list_of_cols:
                # De gecombineerde regex betekent dat de test ook False wordt als er meerdere separators in één kolom zijn gebruikt.

                val = duckdb.sql(fr"""
                SELECT
                    (SELECT COUNT()
                    FROM {table}
                    WHERE regexp_full_match({column}, '^[A-Za-z0-9]+{regex_separator}[A-Za-z0-9]+$')
                    )
                    ==
                    (SELECT COUNT()
                    FROM {table}
                    )
                """).fetchone()[0]
                if val:
                    no_hidden_aggregates = False
                    print(f"kolom {column} bestaat mogelijk uit een verborgen aggregatie")

print(f"Test C: Er zijn geen kolommen die volledig gevuld zijn met mogelijke verborgen aggregaties (bestaande uit een waarde, een scheidingsteken, gevolgd door nog een waarde): {no_hidden_aggregates} \nLet op: als kolommen andersoortige vervuiling hebben, kan deze test een vals negatief zijn")

de volgende scheidingstekens wordt voor gecontroleerd: ['\\.', ',', ', ', ';', '-', ' - ', '_', '\\/', '\\/ ', ' \\/ ', '\\t', '\\|', ':']. (Let op, inclusief escape characters (\) waar dit nodig is voor de code)

Test C: Er zijn geen kolommen die volledig gevuld zijn met mogelijke verborgen aggregaties (bestaande uit een waarde, een scheidingsteken, gevolgd door nog een waarde): True
Let op: als kolommen andersoortige vervuiling hebben, kan deze test een vals negatief zijn

#### Vraag: Zijn er kolommen waarbij het niveau van detail niet voldoet voor het beoogde doel?
**Voor deze vraag is (domein)kennis van de dataset vereist.**

- De X en Y coördinaten impliceren dat de dataset uit punten bestaat, terwijl de werkelijke geometrie uit polygonen bestaat. Deze komen qua detail niet overeen. Het hoofddoel van de dataset op dit moment is om de ligging van de werkelijke archeologie binnen een rijksmonument te kunnen vinden en beoordelen. Een puntcoördinaat is daarvoor niet toereikend. Hoewel X- en Y centroidecoördinaten van polygonen nuttig kunnen zijn, horen deze niet in de basisdataset thuis. Een gebruiker zou deze zelf gemakkelijk weer toe kunnen voegen als diegene de dataset voor een ander doel dan het hoofddoel zou willen gebruiken.

#### Vraag: Staan de waarden en de indicatie van precisie van deze waarde in losse kolommen? Zo ja, is het duidelijk welke precisiekolom bij welke kolom hoort (ook wanneer kolommen gehusseld worden)?

- Niet relevant voor deze dataset

#### Vraag: Is van kolommen waar topografische benamingen in staat duidelijk over welk type geografische eenheid dit gaat?

* Niet relevant voor deze dataset, geen kolommen waar topografische benamingen in staan.

In [62]:
# TODO test D-F zijn voor deze dataset niet relevant en zijn dus overgeslagen

## Dimensie 5: Semantische eenduidigheid en interoperabiliteit
* Vraag: Is er een data dictionary?
    * (Test A: De data dictionary voldoet aan de template van de RCE (notitie Thya: Zo'n template is er (nog) niet, maar mogelijk is dit wel wenselijk?))
* Vraag: Is de data dictionary up-to-date? (notitie Thya: de onderstaande testen zijn alleen mogelijk als er een gestandaardiseerde vorm komt voor de datadictionaries)
    * Test B: De kolommen in de datadictionary kloppen met de kolommen van de dataset.
    * Test C: Er is een omschrijving voor elke tabel van de dataset in de data dictionary.
    * Test D: Er is een omschrijving aanwezig voor elke kolom van de dataset in de data dictionary.
* Vraag: Is er vastgelegd of de kolommen volgens een (standaard) waardenlijst moet worden ingevuld?
* Vraag: Heeft elke kolom die van een linked data standaardwaardenlijkst gebruik maakt ook een kolom voor de uri?
    * Test E: De uri's zijn functioneel en up to date (notitie Thya: nu nog niet toegepast omdat dit op basis van deze dataset niet te testen is).
* Vraag: Voor elke kolom die gebruik maakt van een standaardwaardenlijst die niet gebruik maakt van linked data, is een (online) verbinding met die waardenlijst aanwezig en/of is de waardenlijst verkrijgbaar voor de gebruiker. (notitie Thya: Gezien we hier de omgezette Parquet files aan het testen zijn, is zo'n test denk ik niet mogelijk.)
* Vraag: Zijn er kolommen waar zowel standaard waarden als vrije velden in staan?
    * Test F: Referenties naar (interne) tabellen zijn expliciet in het schema aangegeven. (alleen voor relationele databases)


notitie Thya: De correctheid van de waarden op basis van de standaardwaardenlijsten wordt nu al bij dimensie 3 getest, maar dat zou ook bij deze dimensie kunnen horen. Ik heb nu geinterpreteerd dat hier niet de waarden, maar juist de standaardwaardenlijst zelf wordt gecontroleerd. Test F van deze dimensie zou echter even goed onder dimensie 3 kunnen passen.

#### Vraag: Is er een data dictionary?
**Vereist (domein)kennis van de dataset**

- Er is een datadictionary van een vorige versie van het bestand aanwezig op de G: schijf. Dit is een excel bestand (XLSX): structuur.xlsx

#### Test A
TODO: Er is nog geen data dictionary template

In [63]:
# TODO er is nog geen data dictionary template
dd_temmplate_match = False

Vraag: Is de data dictionary up-to-date?

- Nee, deze is van een vorige versie. De kolomnamen en hoeveelheid kolommen komen niet (meer) overeen.

#### Test B
(notitie Thya) Nu niet als test toegepast omdat dit niet gestandaardizeerd is en deze code dus niet herhaalbaar zou zijn.
* Nee de kolommen in de dataset en de data dictionary komen niet overeen.

In [64]:
# TODO er is nog geen data dictionary template
dd_columns_match = False

#### Test C
(notitie Thya) Nu niet als test toegepast omdat dit niet gestandaardizeerd is en deze code dus niet herhaalbaar zou zijn.
* Er is maar 1 tabel, en deze is niet omschreven in de data dictionary. (wel elders)

In [65]:
# TODO er is nog geen data dictionary template
dd_table_match = False

#### Test D
(notitie Thya) Nu niet als test toegepast omdat dit niet gestandaardizeerd is en deze code dus niet herhaalbaar zou zijn.
* Nee, niet alle kolommen hebben een omschrijving in de data dictionary

#### Vraag: Is er vastgelegd of de kolommen volgens een (standaard) waardenlijst moet worden ingevuld?
**Voor deze vraag is (domein)kennis van de dataset vereist.**

- Voor cpx_code_o, cpx_code_n, cpx_begin en cpx_eind_p is dit goed aangegeven.
- Voor cpx_code_b is niet duidelijk aangegeven dat deze omschrijvingen ook uit het ABR komen.

#### Vraag: Heeft elke kolom die van een linked data standaardwaardenlijkst gebruik maakt ook een kolom voor de uri, of alternatief (voor relationele databases) is er een tabel aanwezig met de waarde gekoppeld aan de uri?
(notitie Thya: Als er een gestandaardizeerde manier is om deze qua naam aan elkaar te relateren, zou dat mooi zijn.

- De referentielijsten zijn linked data maar er is géén uri beschikbaar.

#### Test E
In deze dataset zijn uris nog niet geintegreerd, dus op basis van deze dataset kan ik daar nog geen code voor schrijven.

In [66]:
# TODO: Check voor kolommen met uris of deze alleen en correcte response geven, en voor de juiste waarde zijn.

#### Vraag: Voor elke kolom die gebruik maakt van een standaardwaardenlijst die niet gebruik maakt van linked data, is een (online) verbinding met die waardenlijst aanwezig, is de waardenlijst in de dataset geintegreerd, en/of is de waardenlijst op een andere manier verkrijgbaar voor de gebruiker.
**Vereist (domein)kennis van de dataset.**

- n.v.t.: Standaardwaarden zijn wel linked data

#### Test F

In [67]:
# TODO ik weet nog niet of dit mogelijk is in duckdb, en hoe dat dan zou moeten... Dit gaat mijn kennis even te boven.

## Dimensie 6: Ruimtelijke referentie-eenduidigheid

Alleen van toepassing als het een ruimtelijke dataset betreft (maar let op: ook niet GIS-ready datasets bevatten vaak ruimtelijke informatie)
* Vraag: Zijn locaties expliciet gemaakt, of zijn er alleen omschrijvingen? (let op: hier wordt niet alleen geometrie bedoeld, maar ook bijvoorbeeld provincies, adressen, etc.)
    * Test A: Er is een expliciete geometrie-kolom aanwezig.
    * Test B: Er is een expliciet coordinaatreferentiestelsel aanwezig.
* Vraag: Volgen de (niet-geometrische) locatiekolommen een expliciete standaard?
    * Test C: Naamgeving van Nederlandse bestuurlijke gebieden (land, provincie, gemeente) komt overeen met de Basisregistratie Kadaster (BRK) (vergelijking Bestuurlijke gebieden)
    * Test D: Naamgeving en samenstelling van adressen komt overeen met de basisregistratie Kadaster (vergelijking Basisregistratie Adressen en Gebouwen)
        * D 1: Voor adressen die in 1 kolom staan
        * D 2: Voor adressen die verdeeld zijn over meerdere kolommen.
    * Test E: Bij datasets die zowel geometrieën en bestuurlijke gebieden hebben, hebben deze overlap in geometrie (vergelijking Bestuurlijke Gebieden).
    * Test F: Datasets die binnen Nederland zouden moeten liggen, hebben geen geometrieën die buiten Nederland liggen. (vergelijking Bestuurlijke Gebieden en noordzee polygoon).
    * Test G: kolommen met wkt informatie kunnen worden omgezet naar geometrie
    * Test H: kolommen met x en y coordinaten kunnen worden omgezet naar geometrie
* Vraag: Is de ruimtelijke informatie binnen kolommen op hetzelfde niveau van detail (als het geen geometrie betreft)
* Vraag:
    * Test I: polygoongeometrieën zijn valide (niet zelf-kruisend, geen gaten, aansluitend)

#### Vraag: Zijn locaties expliciet gemaakt, of zijn er alleen omschrijvingen?

(maar let op: ook niet GIS-ready datasets bevatten vaak ruimtelijke informatie)

Ja, geometrie is aanwezig.

#### Test A

In [68]:
table_has_geometry = duckdb.sql(f"""
SELECT
    CASE WHEN EXISTS(
        SELECT *
        FROM information_schema.columns
        WHERE table_schema = '{schema}'
        AND table_name = '{table_name}'
        AND CONTAINS(data_type, 'GEOMETRY'))
    THEN True
    ELSE False
    END;""").fetchone()[0]

print(f"Er is een expliciete geometrie-kolom aanwezig: {table_has_geometry}")

Er is een expliciete geometrie-kolom aanwezig: True

#### Test B

In [69]:
table_has_geometry = duckdb.sql(fr"""
SELECT
    CASE WHEN EXISTS
        (
        SELECT *
        FROM information_schema.columns
        WHERE table_schema = '{schema}'
        AND table_name = '{table_name}'
        AND regexp_matches(data_type, 'GEOMETRY\(''EPSG:[0-9]+''\)')
        )
    THEN True
    ELSE False
    END;""").fetchone()[0]

print(f"Er is een expliciete geometrie-kolom aanwezig: {table_has_geometry}")

Er is een expliciete geometrie-kolom aanwezig: True

#### Vraag: Volgen de (niet-geometrische) locatiekolommen een expliciete standaard?
**Vereist (domein)kennis van de dataset**

* kolommen cpx_x_coor en cpx_y_coor zijn coordinaten in EPSG:28992, maar dit is niet expliciet terug te vinden, en het is niet duidelijk hoe deze zich verhouden tot de polygonen. Hoogstwaarschijnlijk zijn het centroiden, maar op welke manier deze zijn gegenereerd is onbekend.
* Er zijn geen andere kolommen die een locatie-indicate bevatten.

#### Test C
Kan hier niet getest worden, dataset bevat dergelijke kolommen niet

In [70]:
naamgeving_bg_correct = True
# TODO nu overgeslagen, voor volgende dataset implementeren
print(f"Test C: Naamgeving van Nederlandse bestuurlijke gebieden (land, provincie, gemeente) komt overeen met de Basisregistratie Kadaster; {naamgeving_bg_correct}")

Test C: Naamgeving van Nederlandse bestuurlijke gebieden (land, provincie, gemeente) komt overeen met de Basisregistratie Kadaster; True

#### Test D
Kan hier niet getest worden, dataset bevat dergelijke kolommen niet.

In [71]:
naamgeving_adressen_correct = True
# TODO nu overgeslagen, voor volgende dataset implementeren.
print(f"Test D: Naamgeving en samenstelling van adressen komt overeen met de basisregistratie Kadaster: {naamgeving_adressen_correct}")

Test D: Naamgeving en samenstelling van adressen komt overeen met de basisregistratie Kadaster: True

#### Test E
Kan hier niet getes worden, dataset bevat dergelijke kolommen niet.

In [72]:
geom_in_correct_bg = True
# TODO nu overgeslagen, voor volgende dataset implementeren.
print(f"Test E: Bij datasets die zowel geometrieën en bestuurlijke gebieden hebben, hebben deze overlap in geometrie (vergelijking Bestuurlijke Gebieden): {geom_in_correct_bg}")

Test E: Bij datasets die zowel geometrieën en bestuurlijke gebieden hebben, hebben deze overlap in geometrie (vergelijking Bestuurlijke Gebieden): True

#### Test F
Kan hier niet getes worden, dataset bevat dergelijke kolommen niet.

In [73]:
# inladen bestuurlijke gebieden
duckdb.sql(f"""
CREATE SCHEMA IF NOT EXISTS brons_bestuurlijke_gebieden_2026;
CREATE TABLE IF NOT EXISTS brons_bestuurlijke_gebieden_2026.landgebied AS
FROM read_parquet('./data/brons/bestuurlijke_gebieden_2026/landgebied.parquet');""")

In [74]:
# testen of alle geometrieën in Nederland liggen.
geom_in_nederland = duckdb.sql(f"""
SELECT
    (
    SELECT COUNT()
    FROM {table}
    WHERE
        ST_WITHIN(geometry, (SELECT geometry FROM brons_bestuurlijke_gebieden_2026.landgebied WHERE "naam" == 'Nederland' LIMIT 1))
    )
    ==
    (
    SELECT COUNT() FROM {table}
    );""").fetchone()[0]


print(f"Test F: Datasets die binnen Nederland zouden moeten liggen, hebben geen geometrieën die buiten Nederland liggen: {geom_in_nederland}")

# TODO dit omvat nu niet onze zeebodem!

Test F: Datasets die binnen Nederland zouden moeten liggen, hebben geen geometrieën die buiten Nederland liggen: False

In [75]:
duckdb.sql(fr"""
    SELECT *
    FROM {table}
    WHERE NOT
        ST_WITHIN(geometry, (SELECT geometry FROM brons_bestuurlijke_gebieden_2026.landgebied WHERE "naam" == 'Nederland' LIMIT 1))
    """).fetchdf()

,complex_id,terreinnum,rijksmonum,cma,cma_volgnr,cpx_monito,cpx_jaar,cpx_code_b,cpx_code_o,cpx_code_n,cpx_begin,cpx_eind_p,cpx_zichtb,cpx_beschr,cpx_kwets,cpx_restau,cpx_consol,cpx_diepte,cpx_diep00,cpx_x_coor,cpx_y_coor,cpx_opmerk,geometry
0,2097.0,1454.0,46078.0,28F-019,None,2864,None,Urnenveld,GVCU|GVX,BGV.UV,Bronstijd laat,IJzertijd vroeg,onbekend,Urnenveld,onbekend,None,None,0.0,0.0,253961.176025,497775.0229,None,"[1, 235, 3, 0, 0, 1, 0, 0, 0, 5, 0, 0, 0, 204,..."
1,18527.0,17003.0,532450.0,NaN,None,0,None,Scheepvaart,ESCH,SV,Nieuwe Tijd A,Nieuwe Tijd A,nee,Resten van een zeventiende-eeuwse koopvaarder.,ja,None,None,0.0,0.0,105914.000100,563867.4997,None,"[1, 235, 3, 0, 0, 1, 0, 0, 0, 5, 0, 0, 0, 111,..."

## Dimensie 7: Ruimtelijke schaal en resolutie consistentie
* Vraag: Is het schaalniveau van de geometrie gedefinieerd (voor vector datasets)
    * Test A: (zodra mogelijk/er een standaard is voor de data dictionary) De schaal van de vector geometrie staat vastgesteld in de data dictionary.
    * Test B: De schaal van de vector geometrie staat vastgesteld in de metadata.
* Vraag: Is de resolutie gedefinieerd (voor raster bestanden)
    * Test C: (zodra mogelijk/er een standaard is voor de data dictionary) De resolutie van de raster kaart staat vastgesteld in de data dictionary.
    * Test D: De schaal van de raster kaart staat vastgesteld in the metadata.
* Vraag: Heeft de (vector) geometrie van de dataset over het gehele bestand hetzelfde schaalniveau/resolutie?
* Vraag: Als niet alle geometrieën dezelfde schaal hebben, is dit dan expliciet in de data aangegeven?
* Vraag: Past het schaalniveau/de resolutie bij het beoogde doel?
* Vraag: Komt de minimale precisie van de geometrie overeen met het schaalniveau?
    * Test E: De minimale hoeveelheid cijfers achter de komma van de geometrie komt overeen met het benodigde aantal cijfers achter de komma voor die schaal.

## Dimensie 8: Ruimtelijke geometrische correctheid
* Vraag: Is het geometrietype expliciet?
    * Test A (zodra mogelijk/ er een standaard is voor de data dictionary) het geometrietype van de vector geometrie staat vastgesteld in de data dictionary.
    * Test B: het geomtrietype van de vector geometrie staat vastgesteld in de metadata.
* Test C: Alle geometrieën zijn valide (niet zelfkruisend/niet niet aansluitend/geen gaten)
* Test D: Alle datapunten hebben een geometrie
* Test E: Alle geometrieën hebben data.

## Dimensie 9: Temporele resolutie
* Vraag: Zijn er kolommen voor geldigheid?
    * Test A: Er is een kolom voor begin geldigheid of laatste wijziging
    * Test B: Er is een kolom voor eind geldigheid
    * Test C: Als er zowel een begin- en eindgeldigheid is, ligt de eindgeldigheid dan altijd na de begingeldigheid?
* Vraag: Zijn er kolommen voor wanneer een record is toegevoegd?
    * Test C: Er is een kolom met de datum waarop een record is toegevoegd.
    * Test D: Als er zowel geldigheidskolommen als een registratiedatum kolom is: Begin_geldigheid ligt altijd *op of na* de registratiedatum
    * Test E: Als er zowel geldigheidskolommen als een registratiedatum kolom is: Eind_geldigheid ligt altijd *na* de registratiedatum
* Vraag: Worden verouderde datapunten bewaard? (bijvoorbeeld in de vorm van legacy/historische bestanden, time travel in de originele database, of in de dataset zelf)
* Vraag: Is de updatefrequentie vastgelegd? En komt de werkelijke updatefrequentie overeen met de updatefrequentie in de praktijk?

(zie Dimensie 3 voor het testen van de tijdsstandaard ISO 8601, ook voor de geldigheidskolommen).